/**
 * Korean verb seed list — ~150 high-frequency verbs and adjectives.
 *
 * Each entry feeds the conjugation engine to generate ~13 cards per verb.
 * `irreg` markers: regular | hada | b | d | s | l | reu | eu.
 * `unit` decides which unit the generated conjugation cards go into.
 * `honorificOverride` sets a suppletive honorific form (e.g. 먹다 → 드세요).
 *
 * Romanization is read by the engine via `rom` (the dictionary-form
 * Revised Romanization). Conjugation card romanizations are generated by a
 * lightweight romanizer in build-korean-db.cjs.
 */

module.exports.VERBS = [
  // ── Motion ───────────────────────────────────────────────────────────────────
  { dict: '가다',     en: 'to go',                  rom: 'gada',     irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '오다',     en: 'to come',                rom: 'oda',      irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '들어가다', en: 'to enter',               rom: 'deureogada', irreg: 'regular', pos: 'verb', unit: 'ko-unit-15' },
  { dict: '나가다',   en: 'to go out',              rom: 'nagada',   irreg: 'regular', pos: 'verb', unit: 'ko-unit-15' },
  { dict: '올라가다', en: 'to go up',               rom: 'ollagada', irreg: 'regular', pos: 'verb', unit: 'ko-unit-15' },
  { dict: '내려가다', en: 'to go down',             rom: 'naeryeogada', irreg: 'regular', pos: 'verb', unit: 'ko-unit-15' },
  { dict: '돌아가다', en: 'to go back / return',    rom: 'doragada', irreg: 'regular', pos: 'verb', unit: 'ko-unit-15' },
  { dict: '걷다',     en: 'to walk',                rom: 'geotda',   irreg: 'd',       pos: 'verb', unit: 'ko-unit-15' },
  { dict: '뛰다',     en: 'to run / jump',          rom: 'ttwida',   irreg: 'regular', pos: 'verb', unit: 'ko-unit-15' },
  { dict: '타다',     en: 'to ride / take (transport)', rom: 'tada', irreg: 'regular', pos: 'verb', unit: 'ko-unit-15' },
  { dict: '내리다',   en: 'to get off',             rom: 'naerida',  irreg: 'regular', pos: 'verb', unit: 'ko-unit-15' },
  { dict: '도착하다', en: 'to arrive',              rom: 'dochakhada', irreg: 'hada',  pos: 'verb', unit: 'ko-unit-15' },
  { dict: '출발하다', en: 'to depart',              rom: 'chulbalhada', irreg: 'hada', pos: 'verb', unit: 'ko-unit-15' },
  { dict: '여행하다', en: 'to travel',              rom: 'yeohaenghada', irreg: 'hada', pos: 'verb', unit: 'ko-unit-15' },

  // ── Eating / drinking ───────────────────────────────────────────────────────
  { dict: '먹다',     en: 'to eat',                 rom: 'meokda',   irreg: 'regular', pos: 'verb', unit: 'ko-unit-06', honorificOverride: '드세요' },
  { dict: '마시다',   en: 'to drink',               rom: 'masida',   irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '요리하다', en: 'to cook',                rom: 'yorihada', irreg: 'hada',    pos: 'verb', unit: 'ko-unit-05' },
  { dict: '맛보다',   en: 'to taste',               rom: 'matboda',  irreg: 'regular', pos: 'verb', unit: 'ko-unit-05' },
  { dict: '주문하다', en: 'to order (food)',        rom: 'jumunhada', irreg: 'hada',   pos: 'verb', unit: 'ko-unit-09' },

  // ── Daily life ──────────────────────────────────────────────────────────────
  { dict: '하다',     en: 'to do',                  rom: 'hada',     irreg: 'hada',    pos: 'verb', unit: 'ko-unit-06' },
  { dict: '있다',     en: 'to exist / have',        rom: 'itda',     irreg: 'regular', pos: 'verb', unit: 'ko-unit-06', honorificOverride: '계세요' },
  { dict: '없다',     en: 'to not exist / not have', rom: 'eopda',   irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '주다',     en: 'to give',                rom: 'juda',     irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '받다',     en: 'to receive',             rom: 'batda',    irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '사다',     en: 'to buy',                 rom: 'sada',     irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '팔다',     en: 'to sell',                rom: 'palda',    irreg: 'l',       pos: 'verb', unit: 'ko-unit-16' },
  { dict: '쓰다',     en: 'to write / use',         rom: 'sseuda',   irreg: 'eu',      pos: 'verb', unit: 'ko-unit-06' },
  { dict: '읽다',     en: 'to read',                rom: 'ikda',     irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '말하다',   en: 'to speak / say',         rom: 'malhada',  irreg: 'hada',    pos: 'verb', unit: 'ko-unit-06' },
  { dict: '듣다',     en: 'to listen',              rom: 'deutda',   irreg: 'd',       pos: 'verb', unit: 'ko-unit-06' },
  { dict: '보다',     en: 'to see / watch',         rom: 'boda',     irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '만나다',   en: 'to meet',                rom: 'mannada',  irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '자다',     en: 'to sleep',               rom: 'jada',     irreg: 'regular', pos: 'verb', unit: 'ko-unit-06', honorificOverride: '주무세요' },
  { dict: '일어나다', en: 'to wake up / stand up',  rom: 'ireonada', irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '쉬다',     en: 'to rest',                rom: 'swida',    irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '입다',     en: 'to wear (clothes)',      rom: 'ipda',     irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '벗다',     en: 'to take off (clothes)',  rom: 'beotda',   irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '씻다',     en: 'to wash',                rom: 'ssitda',   irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '청소하다', en: 'to clean',               rom: 'cheongsohada', irreg: 'hada', pos: 'verb', unit: 'ko-unit-06' },

  // ── Communication ──────────────────────────────────────────────────────────
  { dict: '묻다',     en: 'to ask',                 rom: 'mutda',    irreg: 'd',       pos: 'verb', unit: 'ko-unit-06' },
  { dict: '대답하다', en: 'to answer',              rom: 'daedaphada', irreg: 'hada',  pos: 'verb', unit: 'ko-unit-06' },
  { dict: '전화하다', en: 'to call (phone)',        rom: 'jeonhwahada', irreg: 'hada', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '쓰다',     en: 'to write',               rom: 'sseuda',   irreg: 'eu',     pos: 'verb', unit: 'ko-unit-06', skip: true }, // dup, removed by id
  { dict: '설명하다', en: 'to explain',             rom: 'seolmyeonghada', irreg: 'hada', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '소개하다', en: 'to introduce',           rom: 'sogaehada', irreg: 'hada',   pos: 'verb', unit: 'ko-unit-06' },

  // ── Cognition ──────────────────────────────────────────────────────────────
  { dict: '알다',     en: 'to know',                rom: 'alda',     irreg: 'l',       pos: 'verb', unit: 'ko-unit-06' },
  { dict: '모르다',   en: 'to not know',            rom: 'moreuda',  irreg: 'reu',     pos: 'verb', unit: 'ko-unit-06' },
  { dict: '생각하다', en: 'to think',               rom: 'saenggakhada', irreg: 'hada', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '기억하다', en: 'to remember',            rom: 'gieokhada', irreg: 'hada',  pos: 'verb', unit: 'ko-unit-06' },
  { dict: '잊다',     en: 'to forget',              rom: 'itda',     irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '이해하다', en: 'to understand',          rom: 'ihaehada', irreg: 'hada',    pos: 'verb', unit: 'ko-unit-06' },
  { dict: '배우다',   en: 'to learn',               rom: 'baeuda',   irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '가르치다', en: 'to teach',               rom: 'gareuchida', irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '공부하다', en: 'to study',               rom: 'gongbuhada', irreg: 'hada',  pos: 'verb', unit: 'ko-unit-06' },
  { dict: '연습하다', en: 'to practise',            rom: 'yeonseuphada', irreg: 'hada', pos: 'verb', unit: 'ko-unit-06' },

  // ── Emotion / feeling ──────────────────────────────────────────────────────
  { dict: '좋아하다', en: 'to like',                rom: 'joahada',  irreg: 'hada',    pos: 'verb', unit: 'ko-unit-06' },
  { dict: '싫어하다', en: 'to dislike',             rom: 'silheohada', irreg: 'hada',  pos: 'verb', unit: 'ko-unit-06' },
  { dict: '사랑하다', en: 'to love',                rom: 'saranghada', irreg: 'hada',  pos: 'verb', unit: 'ko-unit-06' },
  { dict: '느끼다',   en: 'to feel',                rom: 'neukkida', irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '울다',     en: 'to cry',                 rom: 'ulda',     irreg: 'l',       pos: 'verb', unit: 'ko-unit-06' },
  { dict: '웃다',     en: 'to laugh / smile',       rom: 'utda',     irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '걱정하다', en: 'to worry',               rom: 'geokjeonghada', irreg: 'hada', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '놀라다',   en: 'to be surprised',        rom: 'nollada',  irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '화내다',   en: 'to get angry',           rom: 'hwanaeda', irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },

  // ── Working / making ──────────────────────────────────────────────────────
  { dict: '일하다',   en: 'to work',                rom: 'ilhada',   irreg: 'hada',    pos: 'verb', unit: 'ko-unit-06' },
  { dict: '만들다',   en: 'to make',                rom: 'mandeulda', irreg: 'l',     pos: 'verb', unit: 'ko-unit-06' },
  { dict: '짓다',     en: 'to build',               rom: 'jitda',    irreg: 's',       pos: 'verb', unit: 'ko-unit-06' },
  { dict: '고치다',   en: 'to fix',                 rom: 'gochida',  irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '쓰다',     en: 'to use',                 rom: 'sseuda',   irreg: 'eu',      pos: 'verb', unit: 'ko-unit-06', skip: true },
  { dict: '돕다',     en: 'to help',                rom: 'dopda',    irreg: 'b',       pos: 'verb', unit: 'ko-unit-06' },
  { dict: '바꾸다',   en: 'to change',              rom: 'bakkuda',  irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '시작하다', en: 'to start',               rom: 'sijakhada', irreg: 'hada',   pos: 'verb', unit: 'ko-unit-06' },
  { dict: '끝나다',   en: 'to end / finish',        rom: 'kkeutnada', irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '계속하다', en: 'to continue',            rom: 'gyesokhada', irreg: 'hada',  pos: 'verb', unit: 'ko-unit-06' },

  // ── Adjectives (state/quality) ─────────────────────────────────────────────
  { dict: '좋다',     en: 'to be good',             rom: 'jota',     irreg: 'regular', pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '나쁘다',   en: 'to be bad',              rom: 'nappeuda', irreg: 'eu',      pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '크다',     en: 'to be big',              rom: 'keuda',    irreg: 'eu',      pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '작다',     en: 'to be small',            rom: 'jakda',    irreg: 'regular', pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '많다',     en: 'to be many / much',      rom: 'manta',    irreg: 'regular', pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '적다',     en: 'to be few / little',     rom: 'jeokda',   irreg: 'regular', pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '예쁘다',   en: 'to be pretty',           rom: 'yeppeuda', irreg: 'eu',      pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '아름답다', en: 'to be beautiful',        rom: 'areumdapda', irreg: 'b',     pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '귀엽다',   en: 'to be cute',             rom: 'gwiyeopda', irreg: 'b',     pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '잘생기다', en: 'to be handsome',         rom: 'jalsaenggida', irreg: 'regular', pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '맛있다',   en: 'to be delicious',        rom: 'masitda',  irreg: 'regular', pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '맛없다',   en: 'to be tasteless',        rom: 'maseopda', irreg: 'regular', pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '재미있다', en: 'to be fun / interesting', rom: 'jaemiitda', irreg: 'regular', pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '재미없다', en: 'to be boring',           rom: 'jaemieopda', irreg: 'regular', pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '쉽다',     en: 'to be easy',             rom: 'swipda',   irreg: 'b',       pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '어렵다',   en: 'to be difficult',        rom: 'eoryeopda', irreg: 'b',     pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '빠르다',   en: 'to be fast',             rom: 'ppareuda', irreg: 'reu',     pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '느리다',   en: 'to be slow',             rom: 'neurida',  irreg: 'regular', pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '높다',     en: 'to be tall / high',      rom: 'nopda',    irreg: 'regular', pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '낮다',     en: 'to be low',              rom: 'natda',    irreg: 'regular', pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '길다',     en: 'to be long',             rom: 'gilda',    irreg: 'l',       pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '짧다',     en: 'to be short',            rom: 'jjalpda',  irreg: 'regular', pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '뜨겁다',   en: 'to be hot (object)',     rom: 'tteugeopda', irreg: 'b',    pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '차갑다',   en: 'to be cold (object)',    rom: 'chagapda', irreg: 'b',       pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '덥다',     en: 'to be hot (weather)',    rom: 'deopda',   irreg: 'b',       pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '춥다',     en: 'to be cold (weather)',   rom: 'chupda',   irreg: 'b',       pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '따뜻하다', en: 'to be warm',             rom: 'ttatteuthada', irreg: 'hada', pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '시원하다', en: 'to be cool / refreshing', rom: 'siwonhada', irreg: 'hada',  pos: 'adjective', unit: 'ko-unit-06' },

  // ── Emotional state (adjectives) ───────────────────────────────────────────
  { dict: '행복하다', en: 'to be happy',            rom: 'haengbokhada', irreg: 'hada', pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '슬프다',   en: 'to be sad',              rom: 'seulpeuda', irreg: 'eu',    pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '기쁘다',   en: 'to be glad',             rom: 'gippeuda', irreg: 'eu',      pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '화나다',   en: 'to be angry',            rom: 'hwanada',  irreg: 'regular', pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '무섭다',   en: 'to be scary / scared',   rom: 'museopda', irreg: 'b',       pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '심심하다', en: 'to be bored',            rom: 'simsimhada', irreg: 'hada',  pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '피곤하다', en: 'to be tired',            rom: 'pigonhada', irreg: 'hada',   pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '아프다',   en: 'to be sick / hurt',      rom: 'apeuda',   irreg: 'eu',      pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '바쁘다',   en: 'to be busy',             rom: 'bappeuda', irreg: 'eu',      pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '한가하다', en: 'to be free / not busy',  rom: 'hangahada', irreg: 'hada',   pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '배고프다', en: 'to be hungry',           rom: 'baegopeuda', irreg: 'eu',    pos: 'adjective', unit: 'ko-unit-06' },
  { dict: '목마르다', en: 'to be thirsty',          rom: 'mongmareuda', irreg: 'reu', pos: 'adjective', unit: 'ko-unit-06' },

  // ── Colors as descriptive verbs (note: most are normally used as 색 + noun) ──
  { dict: '빨갛다',   en: 'to be red',              rom: 'ppalgata', irreg: 'regular', pos: 'adjective', unit: 'ko-unit-21' },
  { dict: '파랗다',   en: 'to be blue',             rom: 'parata',   irreg: 'regular', pos: 'adjective', unit: 'ko-unit-21' },
  { dict: '노랗다',   en: 'to be yellow',           rom: 'norata',   irreg: 'regular', pos: 'adjective', unit: 'ko-unit-21' },
  { dict: '하얗다',   en: 'to be white',            rom: 'hayata',   irreg: 'regular', pos: 'adjective', unit: 'ko-unit-21' },
  { dict: '까맣다',   en: 'to be black',            rom: 'kkamata',  irreg: 'regular', pos: 'adjective', unit: 'ko-unit-21' },

  // ── More everyday verbs ─────────────────────────────────────────────────────
  { dict: '되다',     en: 'to become',              rom: 'doeda',    irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '살다',     en: 'to live',                rom: 'salda',    irreg: 'l',       pos: 'verb', unit: 'ko-unit-06' },
  { dict: '죽다',     en: 'to die',                 rom: 'jukda',    irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '태어나다', en: 'to be born',             rom: 'taeeonada', irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '결혼하다', en: 'to marry',               rom: 'gyeolhonhada', irreg: 'hada', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '들다',     en: 'to lift / hold',         rom: 'deulda',   irreg: 'l',       pos: 'verb', unit: 'ko-unit-06' },
  { dict: '놓다',     en: 'to put down / place',    rom: 'nota',     irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '잡다',     en: 'to catch / grab',        rom: 'japda',    irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '놓치다',   en: 'to miss / let slip',     rom: 'notchida', irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '찾다',     en: 'to look for / find',     rom: 'chatda',   irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '잃다',     en: 'to lose (an item)',      rom: 'ilta',     irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '기다리다', en: 'to wait',                rom: 'gidarida', irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '늦다',     en: 'to be late',             rom: 'neutda',   irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '서두르다', en: 'to hurry',               rom: 'seodureuda', irreg: 'reu',  pos: 'verb', unit: 'ko-unit-06' },
  { dict: '준비하다', en: 'to prepare',             rom: 'junbihada', irreg: 'hada',   pos: 'verb', unit: 'ko-unit-06' },
  { dict: '결정하다', en: 'to decide',              rom: 'gyeoljeonghada', irreg: 'hada', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '확인하다', en: 'to check / confirm',     rom: 'hwaginhada', irreg: 'hada',  pos: 'verb', unit: 'ko-unit-06' },
  { dict: '약속하다', en: 'to promise',             rom: 'yaksokhada', irreg: 'hada',  pos: 'verb', unit: 'ko-unit-06' },
  { dict: '도와주다', en: 'to help (give help)',    rom: 'dowajuda', irreg: 'regular', pos: 'verb', unit: 'ko-unit-06' },
  { dict: '여행하다', en: 'to travel',              rom: 'yeohaenghada', irreg: 'hada', pos: 'verb', unit: 'ko-unit-15', skip: true },
  { dict: '운전하다', en: 'to drive',               rom: 'unjeonhada', irreg: 'hada',  pos: 'verb', unit: 'ko-unit-15' },
  { dict: '운동하다', en: 'to exercise',            rom: 'undonghada', irreg: 'hada',  pos: 'verb', unit: 'ko-unit-25' },
  { dict: '노래하다', en: 'to sing',                rom: 'noraehada', irreg: 'hada',   pos: 'verb', unit: 'ko-unit-25' },
  { dict: '춤추다',   en: 'to dance',               rom: 'chumchuda', irreg: 'regular', pos: 'verb', unit: 'ko-unit-25' },
  { dict: '놀다',     en: 'to play / hang out',     rom: 'nolda',    irreg: 'l',       pos: 'verb', unit: 'ko-unit-25' },
  { dict: '이기다',   en: 'to win',                 rom: 'igida',    irreg: 'regular', pos: 'verb', unit: 'ko-unit-25' },
  { dict: '지다',     en: 'to lose (a game)',       rom: 'jida',     irreg: 'regular', pos: 'verb', unit: 'ko-unit-25' },
];

// Drop the few that were marked skip:true (duplicates I left in for clarity above)
module.exports.VERBS = module.exports.VERBS.filter(v => !v.skip);
