/**
 * Korean vocabulary — substantial expansion mirroring the Swahili unit structure.
 *
 * Each unit roughly maps to its Swahili counterpart (Colours, Animals, Body Parts,
 * Travel, Shopping, Tech, Sports, Religion, School/Work, Emotions, etc.).
 * Romanization is Revised Romanization, written by rule.
 *
 * Hand-curated for quality; a review pass for native-speaker idiomaticity will
 * follow per the user's plan.
 */

// Compact builder: V(unit, ko, en, rom, opts?) → vocabulary card spec.
function V(unit, ko, en, rom, opts = {}) {
  return { unit, ko, en, rom, type: 'vocabulary', pos: opts.pos || 'noun', ...opts };
}
function P(unit, ko, en, rom, opts = {}) {
  return { unit, ko, en, rom, type: 'phrase', pos: 'phrase', register: opts.register || 'formal', ...opts };
}

module.exports.UNITS_EXTRA = [
  // [id, name, description, level, order_index, track, grammar_notes]
  ['ko-unit-15', 'Travel & Transport',         'Trains, taxis, planes, and the words you need to get there.',                                  2, 15, 'vocabulary', ''],
  ['ko-unit-16', 'Shopping & Money',           'Prices, change, payment, and the language of the Korean market.',                              2, 16, 'vocabulary', ''],
  ['ko-unit-17', 'Body & Health',              'Symptoms, pharmacy, doctor visits — the words you hope you don\'t need.',                      2, 17, 'vocabulary', ''],
  ['ko-unit-18', 'Body Parts',                 'From head (머리) to toe — naming the body.',                                                    1, 18, 'vocabulary', ''],
  ['ko-unit-19', 'Colors & Descriptions',      'Colours and the words that describe size, shape, and quality.',                                 1, 19, 'vocabulary', ''],
  ['ko-unit-20', 'Clothing & Appearance',      'What people wear and how they look.',                                                            1, 20, 'vocabulary', ''],
  ['ko-unit-21', 'Color Adjectives',           'Colour adjectives in their predicate form — 빨갛다, 파랗다.',                                     2, 21, 'vocabulary', ''],
  ['ko-unit-22', 'Animals',                    'Pets, farm animals, wild animals, sea creatures.',                                              1, 22, 'vocabulary', ''],
  ['ko-unit-23', 'Weather & Environment',      'The four seasons, weather words, the natural world.',                                           2, 23, 'vocabulary', ''],
  ['ko-unit-24', 'Technology & Modern Life',   'Phones, the internet, apps — the everyday digital world.',                                     2, 24, 'vocabulary', ''],
  ['ko-unit-25', 'Sports & Recreation',        'Sports Koreans love (especially football and baseball), hobbies, leisure.',                    2, 25, 'vocabulary', ''],
  ['ko-unit-26', 'Music, Movies & Drama',      'K-pop, K-dramas, films — Korea\'s cultural exports as everyday vocabulary.',                   2, 26, 'vocabulary', ''],
  ['ko-unit-27', 'Education & School',         'School subjects, life at university, study culture.',                                           2, 27, 'vocabulary', ''],
  ['ko-unit-28', 'Work & Office Life',         'The vocabulary of Korean corporate culture — 회사, 야근, 사장님.',                              3, 28, 'vocabulary', ''],
  ['ko-unit-29', 'Emotions',                   'Feelings and moods, beyond happy and sad.',                                                     2, 29, 'vocabulary', ''],
  ['ko-unit-30', 'Abstract Nouns',             'Truth, freedom, justice — the words for ideas, not things.',                                    3, 30, 'vocabulary', ''],
  ['ko-unit-31', 'Adverbs & Connectors',       'How, when, however — the glue between ideas.',                                                  2, 31, 'vocabulary', ''],
  ['ko-unit-32', 'House & Home',               'Rooms, furniture, household items — Korean home life.',                                         1, 32, 'vocabulary', ''],
  ['ko-unit-33', 'Nature',                     'Mountains, rivers, the sea — Korea\'s geographic vocabulary.',                                  2, 33, 'vocabulary', ''],
  ['ko-unit-34', 'Religion & Spirituality',    'Buddhism, Christianity, shamanism, Confucianism — religion in Korean life.',                    3, 34, 'vocabulary', ''],
  ['ko-unit-35', 'Korean Pop Culture',         '한류 (the Korean Wave) — fandom vocabulary, mukbang, internet slang.',                          2, 35, 'vocabulary', ''],
  ['ko-unit-36', 'Idioms & Proverbs',          'Sayings (속담) and idioms (관용어) — wisdom packed into a phrase.',                              3, 36, 'vocabulary', ''],
  ['ko-unit-37', 'Politics & Society',         'Government, elections, the news.',                                                              3, 37, 'vocabulary', ''],
  ['ko-unit-38', 'Business & Finance',         'Money, business, economics — Korean financial life.',                                           3, 38, 'vocabulary', ''],
  ['ko-unit-39', 'Communication & Media',      'TV, radio, social media — how Koreans communicate.',                                            2, 39, 'vocabulary', ''],
  ['ko-unit-40', 'Discourse & Connectors',     'Discourse markers, advanced connectors, the tools of fluent conversation.',                     3, 40, 'vocabulary', ''],
];

// ── CARDS: each entry is V(unit, ko, en, rom, opts?) or P() ──────────────────────
module.exports.VOCAB = [
  // ═══════════════ Existing-unit expansions ═══════════════════════════════════

  // ── Unit 1: First Words (expansion) ──────────────────────────────────────────
  P('ko-unit-01', '오랜만이에요',        'long time no see',                            'oraenmanieyo'),
  P('ko-unit-01', '잘 지내세요?',         'how are you doing?',                          'jal jinaeseyo?'),
  P('ko-unit-01', '잘 지내요',            "I'm doing well",                              'jal jinaeyo'),
  P('ko-unit-01', '처음 뵙겠습니다',      'how do you do (first meeting)',               'cheoeum boepgesseumnida'),
  P('ko-unit-01', '안녕히 주무세요',      'good night (to someone going to sleep)',      'annyeonghi jumuseyo'),
  P('ko-unit-01', '잘 자요',              'good night (casual)',                          'jal jayo', { register: 'informal' }),
  P('ko-unit-01', '좋은 아침이에요',      'good morning',                                 'joeun achimieyo'),
  P('ko-unit-01', '천만에요',             "you're welcome",                              'cheonmaneyo'),
  P('ko-unit-01', '아니에요',             'no / not at all',                              'anieyo'),
  P('ko-unit-01', '괜찮아요',             "I'm fine / it's okay",                        'gwaenchanayo'),
  P('ko-unit-01', '미안해요',             "I'm sorry (polite)",                          'mianhaeyo'),

  // ── Unit 2: Basics (expansion) ───────────────────────────────────────────────
  V('ko-unit-02', '사람',     'person',                  'saram'),
  V('ko-unit-02', '친구',     'friend',                  'chingu'),
  V('ko-unit-02', '남자',     'man',                     'namja'),
  V('ko-unit-02', '여자',     'woman',                   'yeoja'),
  V('ko-unit-02', '아이',     'child',                   'ai'),
  V('ko-unit-02', '나이',     'age',                     'nai'),
  V('ko-unit-02', '여기',     'here',                    'yeogi', { pos: 'pronoun' }),
  V('ko-unit-02', '거기',     'there',                   'geogi', { pos: 'pronoun' }),
  V('ko-unit-02', '저기',     'over there',              'jeogi', { pos: 'pronoun' }),
  V('ko-unit-02', '이쪽',     'this way',                'ijjok'),
  V('ko-unit-02', '그쪽',     'that way',                'geujjok'),
  V('ko-unit-02', '저쪽',     'that way (over there)',   'jeojjok'),
  V('ko-unit-02', '얼마',     'how much (quantity/price)', 'eolma'),
  V('ko-unit-02', '몇',       'how many',                'myeot'),
  V('ko-unit-02', '어느',     'which',                   'eoneu'),
  V('ko-unit-02', '무슨',     'what kind of',            'museun'),

  // ── Unit 3: Sino-Korean Numbers (expansion) ─────────────────────────────────
  V('ko-unit-03', '십일',  'eleven (11)',     'sibil',     { pos: 'number' }),
  V('ko-unit-03', '십이',  'twelve (12)',     'sibi',      { pos: 'number' }),
  V('ko-unit-03', '십삼',  'thirteen (13)',   'sipsam',    { pos: 'number' }),
  V('ko-unit-03', '이십',  'twenty (20)',     'isip',      { pos: 'number' }),
  V('ko-unit-03', '삼십',  'thirty (30)',     'samsip',    { pos: 'number' }),
  V('ko-unit-03', '사십',  'forty (40)',      'sasip',     { pos: 'number' }),
  V('ko-unit-03', '오십',  'fifty (50)',      'osip',      { pos: 'number' }),
  V('ko-unit-03', '육십',  'sixty (60)',      'yuksip',    { pos: 'number' }),
  V('ko-unit-03', '칠십',  'seventy (70)',    'chilsip',   { pos: 'number' }),
  V('ko-unit-03', '팔십',  'eighty (80)',     'palsip',    { pos: 'number' }),
  V('ko-unit-03', '구십',  'ninety (90)',     'gusip',     { pos: 'number' }),
  V('ko-unit-03', '백만',  'million (1,000,000)', 'baengman', { pos: 'number',
    note: 'Note: 백만 = "100 ten-thousands". Korean counts large numbers by 10,000 (만), not by thousands.' }),
  V('ko-unit-03', '억',    'hundred million (100M)', 'eok', { pos: 'number' }),
  V('ko-unit-03', '원',    'won (Korean currency)', 'won', { pos: 'counter',
    note: 'The Korean monetary unit. Always preceded by Sino-Korean numbers: 만 원 (10,000 won), 십만 원 (100,000 won).' }),

  // ── Unit 8: Native Numbers (expansion) ──────────────────────────────────────
  V('ko-unit-08', '열하나', 'eleven (11)',  'yeolhana',  { pos: 'number' }),
  V('ko-unit-08', '열둘',   'twelve (12)',  'yeoldul',   { pos: 'number' }),
  V('ko-unit-08', '스물',   'twenty (20)',  'seumul',    { pos: 'number',
    note: 'Before a counter: 스무 (스무 살 = 20 years old).' }),
  V('ko-unit-08', '서른',   'thirty (30)',  'seoreun',   { pos: 'number' }),
  V('ko-unit-08', '마흔',   'forty (40)',   'maheun',    { pos: 'number' }),
  V('ko-unit-08', '쉰',     'fifty (50)',   'swin',      { pos: 'number' }),
  V('ko-unit-08', '예순',   'sixty (60)',   'yesun',     { pos: 'number' }),
  V('ko-unit-08', '개',     'thing (general counter)', 'gae', { pos: 'counter',
    note: 'The all-purpose counter for things: 한 개, 두 개, 세 개…' }),
  V('ko-unit-08', '명',     'people counter (polite)', 'myeong', { pos: 'counter',
    note: 'Counter for people: 한 명, 두 명. The honorific form is 분 (e.g. 세 분 — three people, respectful).' }),
  V('ko-unit-08', '분',     'people counter (honorific)', 'bun', { pos: 'counter',
    note: 'Respectful counter for people, used for elders, guests, customers.' }),
  V('ko-unit-08', '마리',   'animals counter',         'mari',   { pos: 'counter' }),
  V('ko-unit-08', '권',     'books counter',           'gwon',   { pos: 'counter' }),
  V('ko-unit-08', '잔',     'cups/glasses counter',    'jan',    { pos: 'counter',
    note: 'Counter for cups, glasses, mugs: 커피 한 잔 (one coffee).' }),
  V('ko-unit-08', '병',     'bottles counter',         'byeong', { pos: 'counter' }),
  V('ko-unit-08', '대',     'machines/vehicles counter', 'dae',  { pos: 'counter' }),

  // ── Unit 4: Everyday Phrases (expansion) ────────────────────────────────────
  P('ko-unit-04', '여기 있어요',           'here you are',                                 'yeogi isseoyo'),
  P('ko-unit-04', '잠시만 기다리세요',     'wait a moment, please',                        'jamsiman gidariseyo'),
  P('ko-unit-04', '안 돼요',                "it can't be done / no good",                  'an dwaeyo'),
  P('ko-unit-04', '돼요',                   "it's okay / it works",                        'dwaeyo'),
  P('ko-unit-04', '진짜요?',                'really?',                                      'jinjjayo?'),
  P('ko-unit-04', '정말요?',                'is that so?',                                  'jeongmaryo?'),
  P('ko-unit-04', '몰라요',                 "I don't know",                                'mollayo'),
  P('ko-unit-04', '뭐예요?',                "what is it?",                                 'mwoyeyo?'),
  P('ko-unit-04', '어떻게 해요?',           'what do I do?',                               'eotteoke haeyo?'),
  P('ko-unit-04', '한국말 잘 못해요',       "I don't speak Korean well",                   'hangungmal jal mothaeyo'),
  P('ko-unit-04', '조심하세요',             'be careful',                                  'josimhaseyo'),
  P('ko-unit-04', '잘 가요',                'go well / take care',                         'jal gayo'),
  P('ko-unit-04', '또 봐요',                'see you again',                               'tto bwayo'),

  // ── Unit 5: Food (expansion) ────────────────────────────────────────────────
  V('ko-unit-05', '국',      'soup',            'guk'),
  V('ko-unit-05', '찌개',    'stew',            'jjigae', { note: 'Thicker, spicier than 국 — eaten communally from a shared pot.' }),
  V('ko-unit-05', '국수',    'noodles',         'guksu'),
  V('ko-unit-05', '냉면',    'cold noodles',    'naengmyeon', { note: 'Buckwheat noodles in icy broth — a summer favourite, originally from the North.' }),
  V('ko-unit-05', '국밥',    'rice in soup',    'gukbap'),
  V('ko-unit-05', '삼겹살',  'grilled pork belly', 'samgyeopsal',
    { note: 'Korea\'s most beloved BBQ cut — grilled at the table, wrapped in lettuce with garlic and ssamjang.' }),
  V('ko-unit-05', '갈비',    'short ribs',      'galbi', { note: 'Marinated beef or pork ribs, grilled at the table.' }),
  V('ko-unit-05', '회',      'raw fish (sashimi)', 'hoe', { note: 'Korean-style raw fish, often eaten with chogochujang or wasabi soy.' }),
  V('ko-unit-05', '잡채',    'stir-fried glass noodles', 'japchae',
    { note: 'Glass noodles with vegetables and meat — a party dish, served at celebrations.' }),
  V('ko-unit-05', '김밥',    'seaweed rice rolls', 'gimbap',
    { note: 'Rice + fillings rolled in seaweed — cheap, portable, the national lunchbox.' }),
  V('ko-unit-05', '죽',      'rice porridge',   'juk', { note: 'Comfort food, eaten when sick.' }),
  V('ko-unit-05', '두부',    'tofu',            'dubu'),
  V('ko-unit-05', '계란',    'egg',             'gyeran'),
  V('ko-unit-05', '고기',    'meat',            'gogi'),
  V('ko-unit-05', '소고기',  'beef',            'sogogi'),
  V('ko-unit-05', '돼지고기', 'pork',           'dwaejigogi'),
  V('ko-unit-05', '닭고기',  'chicken',         'dakgogi'),
  V('ko-unit-05', '생선',    'fish (as food)',  'saengseon'),
  V('ko-unit-05', '야채',    'vegetables',      'yachae'),
  V('ko-unit-05', '과일',    'fruit',           'gwail'),
  V('ko-unit-05', '사과',    'apple',           'sagwa'),
  V('ko-unit-05', '배',      'pear (also: stomach, ship)', 'bae',
    { note: 'Three meanings, distinguished by context: 배 (pear/stomach/ship). Korean pears are large, round, and famously crisp.' }),
  V('ko-unit-05', '딸기',    'strawberry',      'ttalgi'),
  V('ko-unit-05', '바나나',  'banana',          'banana'),
  V('ko-unit-05', '수박',    'watermelon',      'subak'),
  V('ko-unit-05', '귤',      'mandarin / tangerine', 'gyul', { note: 'Jeju Island\'s signature winter fruit.' }),
  V('ko-unit-05', '소금',    'salt',            'sogeum'),
  V('ko-unit-05', '설탕',    'sugar',           'seoltang'),
  V('ko-unit-05', '간장',    'soy sauce',       'ganjang'),
  V('ko-unit-05', '된장',    'fermented soybean paste', 'doenjang',
    { note: 'A foundational seasoning. 된장찌개 (doenjang stew) is the everyday family meal.' }),
  V('ko-unit-05', '고추장',  'red pepper paste','gochujang', { note: 'Sweet-spicy fermented red chili paste — central to Korean flavour.' }),
  V('ko-unit-05', '고춧가루', 'red pepper flakes', 'gochutgaru'),
  V('ko-unit-05', '참기름',  'sesame oil',      'chamgireum'),
  V('ko-unit-05', '마늘',    'garlic',          'maneul', { note: 'Eaten in huge quantities — raw, roasted, in everything.' }),
  V('ko-unit-05', '양파',    'onion',           'yangpa'),
  V('ko-unit-05', '파',      'green onion',     'pa'),
  V('ko-unit-05', '고추',    'chili pepper',    'gochu'),
  V('ko-unit-05', '시장하세요?', 'are you hungry?', 'sijanghaseyo?', { pos: 'phrase', note: 'A polite way to ask if someone is hungry.' }),

  // ── Unit 6: Common Verbs (vocab entries — conjugations generated separately) ─
  // Already populated; nothing additional here.

  // ── Unit 9: Dining (expansion) ──────────────────────────────────────────────
  V('ko-unit-09', '숟가락',  'spoon',           'sutgarak'),
  V('ko-unit-09', '젓가락',  'chopsticks',      'jeotgarak',
    { note: 'Korean chopsticks are flat metal — uniquely Korean. Etiquette: never stick them upright in rice (it resembles a funerary rite).' }),
  V('ko-unit-09', '그릇',    'bowl',            'geureut'),
  V('ko-unit-09', '접시',    'plate',           'jeopsi'),
  V('ko-unit-09', '컵',      'cup / glass',     'keop'),
  V('ko-unit-09', '식탁',    'dining table',    'siktak'),
  V('ko-unit-09', '냅킨',    'napkin',          'naepkin'),
  V('ko-unit-09', '한 잔 더',  'one more glass', 'han jan deo'),
  V('ko-unit-09', '맛',       'taste',          'mat'),
  V('ko-unit-09', '냄새',     'smell',          'naemsae'),
  V('ko-unit-09', '매운맛',   'spicy taste',    'maeunmat',
    { note: 'Korean cuisine is famously hot. Spice tolerance is a point of pride.' }),

  // ── Unit 10: Family (expansion) ─────────────────────────────────────────────
  V('ko-unit-10', '가족',     'family',         'gajok'),
  V('ko-unit-10', '부모님',   'parents',        'bumonim'),
  V('ko-unit-10', '형제',     'siblings',       'hyeongje'),
  V('ko-unit-10', '자매',     'sisters',        'jamae'),
  V('ko-unit-10', '아들',     'son',            'adeul'),
  V('ko-unit-10', '딸',       'daughter',       'ttal'),
  V('ko-unit-10', '남편',     'husband',        'nampyeon'),
  V('ko-unit-10', '아내',     'wife',           'anae'),
  V('ko-unit-10', '결혼',     'marriage',       'gyeolhon'),
  V('ko-unit-10', '이혼',     'divorce',        'ihon'),
  V('ko-unit-10', '아기',     'baby',           'agi'),
  V('ko-unit-10', '청소년',   'teenager / youth', 'cheongsonyeon'),
  V('ko-unit-10', '어른',     'adult',          'eoreun'),
  V('ko-unit-10', '노인',     'elderly person', 'noin'),
  V('ko-unit-10', '친척',     'relative',       'chincheok'),
  V('ko-unit-10', '사촌',     'cousin',         'sachon'),
  V('ko-unit-10', '삼촌',     'uncle (father\'s brother)', 'samchon',
    { note: 'Korean has separate words for paternal vs. maternal uncles/aunts — kinship terms encode the family tree.' }),
  V('ko-unit-10', '이모',     'aunt (mother\'s sister)',   'imo'),
  V('ko-unit-10', '고모',     'aunt (father\'s sister)',   'gomo'),
  V('ko-unit-10', '외삼촌',   'uncle (mother\'s brother)', 'oesamchon'),

  // ── Unit 11: Time & Days (expansion) ────────────────────────────────────────
  V('ko-unit-11', '월요일', 'Monday',     'woryoil'),
  V('ko-unit-11', '화요일', 'Tuesday',    'hwayoil'),
  V('ko-unit-11', '수요일', 'Wednesday',  'suyoil'),
  V('ko-unit-11', '목요일', 'Thursday',   'mogyoil'),
  V('ko-unit-11', '금요일', 'Friday',     'geumyoil'),
  V('ko-unit-11', '토요일', 'Saturday',   'toyoil'),
  V('ko-unit-11', '일요일', 'Sunday',     'iryoil'),
  V('ko-unit-11', '주',     'week',       'ju'),
  V('ko-unit-11', '달',     'month / moon', 'dal'),
  V('ko-unit-11', '년',     'year',       'nyeon'),
  V('ko-unit-11', '계절',   'season',     'gyejeol'),
  V('ko-unit-11', '봄',     'spring',     'bom'),
  V('ko-unit-11', '여름',   'summer',     'yeoreum'),
  V('ko-unit-11', '가을',   'autumn',     'gaeul'),
  V('ko-unit-11', '겨울',   'winter',     'gyeoul'),
  V('ko-unit-11', '시간',   'time / hour', 'sigan'),
  V('ko-unit-11', '날',     'day',        'nal'),
  V('ko-unit-11', '날짜',   'date',       'naljja'),
  V('ko-unit-11', '오전',   'AM / morning', 'ojeon'),
  V('ko-unit-11', '오후',   'PM / afternoon', 'ohu'),
  V('ko-unit-11', '새벽',   'dawn',       'saebyeok'),
  V('ko-unit-11', '한밤중', 'middle of the night', 'hanbamjung'),
  V('ko-unit-11', '평일',   'weekday',    'pyeongil'),

  // ── Unit 12: Places (expansion) ─────────────────────────────────────────────
  V('ko-unit-12', '도시',     'city',          'dosi'),
  V('ko-unit-12', '시골',     'countryside',   'sigol'),
  V('ko-unit-12', '서울',     'Seoul',         'seoul', { note: 'The capital, home to ~half of South Korea\'s population.' }),
  V('ko-unit-12', '부산',     'Busan',         'busan', { note: 'The 2nd-largest city — coastal port, famous for seafood and beaches.' }),
  V('ko-unit-12', '제주도',   'Jeju Island',   'jejudo', { note: 'A volcanic island south of the peninsula — Korea\'s tropical-ish honeymoon destination.' }),
  V('ko-unit-12', '한국',     'Korea',         'hanguk'),
  V('ko-unit-12', '대한민국', 'Republic of Korea (formal)', 'daehanminguk'),
  V('ko-unit-12', '북한',     'North Korea',   'bukhan'),
  V('ko-unit-12', '미국',     'USA',           'miguk'),
  V('ko-unit-12', '일본',     'Japan',         'ilbon'),
  V('ko-unit-12', '중국',     'China',         'jungguk'),
  V('ko-unit-12', '공원',     'park',          'gongwon'),
  V('ko-unit-12', '도서관',   'library',       'doseogwan'),
  V('ko-unit-12', '극장',     'theatre',       'geukjang'),
  V('ko-unit-12', '영화관',   'movie theatre', 'yeonghwagwan'),
  V('ko-unit-12', '백화점',   'department store', 'baekhwajeom'),
  V('ko-unit-12', '미용실',   'hair salon',    'miyongsil'),
  V('ko-unit-12', '은행',     'bank',          'eunhaeng'),
  V('ko-unit-12', '우체국',   'post office',   'ucheguk'),
  V('ko-unit-12', '대학교',   'university',    'daehakgyo'),
  V('ko-unit-12', '교회',     'church',        'gyohoe'),
  V('ko-unit-12', '절',       'Buddhist temple', 'jeol'),

  // ── Unit 13: Cultural Concepts (expansion) ──────────────────────────────────
  V('ko-unit-13', '안녕',     'peace / wellness (the root of the greetings)', 'annyeong',
    { tags: ['culture'], note: 'The same root in 안녕하세요 ("are you at peace?") and 안녕히 가세요 ("go in peace"). Korean greetings ask about peace, not "how are you".' }),
  V('ko-unit-13', '인사',     'a greeting / bow',  'insa', { tags: ['culture'],
    note: 'Greetings (인사) are foundational — bowing, the depth determined by relationship and respect.' }),
  V('ko-unit-13', '체면',     'social face / dignity',  'chemyeon', { tags: ['culture'],
    note: 'Keeping/saving "face" — central to Korean social interaction. Causing someone to lose 체면 is a serious offense.' }),
  V('ko-unit-13', '인연',     'fate / connection',  'inyeon', { tags: ['culture'],
    note: 'The destined connection between people — a chance meeting can be 인연 if it leads to something.' }),
  V('ko-unit-13', '밤문화',   'nightlife culture',  'bammunhwa', { tags: ['culture'],
    note: 'Korea is famous for vibrant late-night culture: 노래방 (karaoke), 포장마차 (street tents), 해장 (hangover food).' }),
  V('ko-unit-13', '찜질방',   'Korean spa / sauna', 'jjimjilbang', { tags: ['culture'],
    note: '24-hour public bathhouses with saunas, hot tubs, and sleeping floors — beloved family destinations.' }),
  V('ko-unit-13', '노래방',   'karaoke room',       'noraebang', { tags: ['culture'],
    note: 'Private singing rooms — a major social activity for friends and after-work teams.' }),

  // ── Unit 14: Holidays (expansion) ───────────────────────────────────────────
  V('ko-unit-14', '연휴',     'consecutive holidays', 'yeonhyu'),
  V('ko-unit-14', '명절',     'traditional holiday',  'myeongjeol', { tags: ['culture'] }),
  V('ko-unit-14', '제사',     'ancestral rites',      'jesa', { tags: ['culture'],
    note: 'Ceremonies honouring ancestors, especially on 설날 and 추석 — food is arranged on a special table in a precise order.' }),
  V('ko-unit-14', '성묘',     'visiting ancestral graves', 'seongmyo', { tags: ['culture'] }),
  V('ko-unit-14', '광복절',   'Liberation Day (Aug 15)', 'gwangbokjeol', { tags: ['culture'],
    note: 'Commemorates liberation from Japanese colonial rule in 1945.' }),
  V('ko-unit-14', '한글날',   'Hangul Day (Oct 9)',     'hangeullal', { tags: ['culture'],
    note: 'Celebrates the creation of the Korean alphabet by King Sejong in 1443. The only national holiday in the world for an alphabet.' }),
  V('ko-unit-14', '어린이날', "Children's Day (May 5)", 'eorininal', { tags: ['culture'] }),
  V('ko-unit-14', '어버이날', "Parents' Day (May 8)",   'eobeoinal', { tags: ['culture'],
    note: 'Children give carnations and gifts to parents. Korea combines Mother\'s and Father\'s Day.' }),

  // ═══════════════ NEW UNITS ════════════════════════════════════════════════

  // ── Unit 15: Travel & Transport ─────────────────────────────────────────────
  V('ko-unit-15', '버스',       'bus',                'beoseu'),
  V('ko-unit-15', '지하철',     'subway',             'jihacheol', { note: 'Seoul has one of the world\'s most extensive, cleanest, and fastest subway networks.' }),
  V('ko-unit-15', '기차',       'train',              'gicha'),
  V('ko-unit-15', 'KTX',        'high-speed train',   'KTX', { note: 'Korea\'s bullet train, Seoul–Busan in 2h 40m.' }),
  V('ko-unit-15', '택시',       'taxi',               'taeksi'),
  V('ko-unit-15', '비행기',     'airplane',           'bihaenggi'),
  V('ko-unit-15', '배',         'boat / ship',        'bae'),
  V('ko-unit-15', '자전거',     'bicycle',            'jajeongeo'),
  V('ko-unit-15', '자동차',     'car',                'jadongcha'),
  V('ko-unit-15', '오토바이',   'motorcycle',         'otobai'),
  V('ko-unit-15', '교통카드',   'transit card',       'gyotongkadeu', { note: 'Rechargeable card (T-money is the main one) for subway, bus, and taxis.' }),
  V('ko-unit-15', '표',         'ticket',             'pyo'),
  V('ko-unit-15', '왕복',       'round trip',         'wangbok'),
  V('ko-unit-15', '편도',       'one way',            'pyeondo'),
  V('ko-unit-15', '출구',       'exit',               'chulgu'),
  V('ko-unit-15', '입구',       'entrance',           'ipgu'),
  V('ko-unit-15', '지도',       'map',                'jido'),
  V('ko-unit-15', '여권',       'passport',           'yeogwon'),
  V('ko-unit-15', '비자',       'visa',               'bija'),
  V('ko-unit-15', '여행',       'travel / trip',      'yeohaeng'),
  V('ko-unit-15', '관광',       'sightseeing',        'gwangwang'),
  V('ko-unit-15', '관광객',     'tourist',            'gwangwanggaek'),
  V('ko-unit-15', '호텔',       'hotel',              'hotel'),
  V('ko-unit-15', '예약',       'reservation',        'yeyak'),
  V('ko-unit-15', '여행가방',   'suitcase',           'yeohaenggabang'),
  V('ko-unit-15', '길',         'road / way',         'gil'),
  V('ko-unit-15', '주소',       'address',            'juso'),
  V('ko-unit-15', '번호',       'number',             'beonho'),
  V('ko-unit-15', '오른쪽',     'right side',         'oreunjjok'),
  V('ko-unit-15', '왼쪽',       'left side',          'oenjjok'),
  V('ko-unit-15', '앞',         'front',              'ap'),
  V('ko-unit-15', '뒤',         'back / behind',      'dwi'),
  V('ko-unit-15', '위',         'above / on top',     'wi'),
  V('ko-unit-15', '아래',       'below / under',      'arae'),
  V('ko-unit-15', '안',         'inside',             'an'),
  V('ko-unit-15', '밖',         'outside',            'bak'),
  V('ko-unit-15', '옆',         'next to / beside',   'yeop'),
  V('ko-unit-15', '근처',       'nearby',             'geuncheo'),
  V('ko-unit-15', '멀다',       'to be far',          'meolda', { pos: 'adjective' }),
  V('ko-unit-15', '가깝다',     'to be close',        'gakkapda', { pos: 'adjective' }),
  V('ko-unit-15', '직진',       'straight ahead',     'jikjin'),
  P('ko-unit-15', '얼마나 멀어요?', 'how far is it?', 'eolmana meoreoyo?'),
  P('ko-unit-15', '여기서 멀어요?', 'is it far from here?', 'yeogiseo meoreoyo?'),

  // ── Unit 16: Shopping & Money ───────────────────────────────────────────────
  V('ko-unit-16', '돈',         'money',              'don'),
  V('ko-unit-16', '현금',       'cash',               'hyeongeum'),
  V('ko-unit-16', '카드',       'card',               'kadeu'),
  V('ko-unit-16', '신용카드',   'credit card',        'sinyongkadeu'),
  V('ko-unit-16', '체크카드',   'debit card',         'chekeukadeu'),
  V('ko-unit-16', '영수증',     'receipt',            'yeongsujeung'),
  V('ko-unit-16', '거스름돈',   'change (money back)', 'geoseureumdon'),
  V('ko-unit-16', '할인',       'discount',           'harin'),
  V('ko-unit-16', '세일',       'sale',               'seil'),
  V('ko-unit-16', '가격',       'price',              'gagyeok'),
  V('ko-unit-16', '값',         'value / price',      'gap'),
  V('ko-unit-16', '비싸다',     'to be expensive',    'bissada', { pos: 'adjective' }),
  V('ko-unit-16', '싸다',       'to be cheap',        'ssada',   { pos: 'adjective' }),
  V('ko-unit-16', '쇼핑',       'shopping',           'syoping'),
  V('ko-unit-16', '가게',       'shop / store',       'gage'),
  V('ko-unit-16', '슈퍼마켓',   'supermarket',        'syupeomaket'),
  V('ko-unit-16', '대형마트',   'big-box store',      'daehyeongmateu'),
  V('ko-unit-16', '동대문',     'Dongdaemun (market)', 'dongdaemun', { note: 'Seoul\'s 24-hour fashion district, famous for wholesale clothing markets.' }),
  V('ko-unit-16', '명동',       'Myeongdong',         'myeongdong', { note: 'Tourist-heavy shopping district in central Seoul.' }),
  V('ko-unit-16', '주문',       'order',              'jumun'),
  V('ko-unit-16', '배달',       'delivery',           'baedal', { note: 'Korea has world-leading food delivery — almost anything, anywhere, often within 30 minutes.' }),
  V('ko-unit-16', '포장',       'takeout / wrapped',  'pojang'),
  V('ko-unit-16', '환불',       'refund',             'hwanbul'),
  V('ko-unit-16', '교환',       'exchange',           'gyohwan'),
  V('ko-unit-16', '서비스',     'free of charge (lit. service)', 'seobiseu',
    { note: 'In Korea, "service" often means something free thrown in — a small dish, a soft drink. Saying "서비스예요" with a smile is generous hospitality.' }),
  V('ko-unit-16', '덤',         'a freebie / extra',  'deom'),
  P('ko-unit-16', '카드 돼요?',          'do you take card?',     'kadeu dwaeyo?'),
  P('ko-unit-16', '깎아 주세요',          'please give a discount', 'kkakka juseyo'),
  P('ko-unit-16', '이거 얼마예요?',      'how much is this?',     'igeo eolmayeyo?'),
  P('ko-unit-16', '봉투 주세요',          'a bag, please',          'bongtu juseyo'),

  // ── Unit 17: Body & Health ──────────────────────────────────────────────────
  V('ko-unit-17', '병원',       'hospital',           'byeongwon'),
  V('ko-unit-17', '의사',       'doctor',             'uisa'),
  V('ko-unit-17', '간호사',     'nurse',              'ganhosa'),
  V('ko-unit-17', '환자',       'patient',            'hwanja'),
  V('ko-unit-17', '약',         'medicine',           'yak'),
  V('ko-unit-17', '약사',       'pharmacist',         'yaksa'),
  V('ko-unit-17', '병',         'illness',            'byeong'),
  V('ko-unit-17', '감기',       'cold (illness)',     'gamgi'),
  V('ko-unit-17', '독감',       'flu',                'dokgam'),
  V('ko-unit-17', '열',         'fever',              'yeol'),
  V('ko-unit-17', '두통',       'headache',           'dutong'),
  V('ko-unit-17', '복통',       'stomach ache',       'boktong'),
  V('ko-unit-17', '치통',       'toothache',          'chitong'),
  V('ko-unit-17', '기침',       'cough',              'gichim'),
  V('ko-unit-17', '콧물',       'runny nose',         'konmul'),
  V('ko-unit-17', '알레르기',   'allergy',            'allereugi'),
  V('ko-unit-17', '주사',       'shot / injection',   'jusa'),
  V('ko-unit-17', '처방전',     'prescription',       'cheobangjeon'),
  V('ko-unit-17', '응급실',     'emergency room',     'eunggeupsil'),
  V('ko-unit-17', '건강',       'health',             'geongang'),
  V('ko-unit-17', '운동',       'exercise',           'undong'),
  V('ko-unit-17', '식이요법',   'diet (eating habits)', 'sigiyobeop'),
  V('ko-unit-17', '몸',         'body',               'mom'),
  V('ko-unit-17', '잠',         'sleep',              'jam'),
  V('ko-unit-17', '꿈',         'dream',              'kkum'),
  V('ko-unit-17', '한의원',     'Korean medicine clinic', 'hanuiwon', { note: 'Traditional Korean medicine clinic — herbal remedies, acupuncture, still widely used.' }),
  V('ko-unit-17', '인삼',       'ginseng',            'insam', { note: 'Korea\'s prized medicinal root — central to traditional medicine and health culture.' }),
  V('ko-unit-17', '한약',       'herbal medicine',    'hanyak' ),
  P('ko-unit-17', '아파요',                'it hurts',                'apayo'),
  P('ko-unit-17', '머리가 아파요',         'I have a headache',       'meoriga apayo'),
  P('ko-unit-17', '열이 나요',             'I have a fever',          'yeori nayo'),
  P('ko-unit-17', '몸이 안 좋아요',         "I don't feel well",       'momi an joayo'),
  P('ko-unit-17', '병원에 가야 해요',        'I need to go to the hospital', 'byeongwone gaya haeyo'),

  // ── Unit 18: Body Parts ─────────────────────────────────────────────────────
  V('ko-unit-18', '머리',     'head / hair',  'meori'),
  V('ko-unit-18', '얼굴',     'face',         'eolgul'),
  V('ko-unit-18', '눈',       'eye / snow',   'nun', { note: 'Two meanings (eye/snow), distinguished by context.' }),
  V('ko-unit-18', '귀',       'ear',          'gwi'),
  V('ko-unit-18', '코',       'nose',         'ko'),
  V('ko-unit-18', '입',       'mouth',        'ip'),
  V('ko-unit-18', '입술',     'lips',         'ipsul'),
  V('ko-unit-18', '이',       'tooth',        'i'),
  V('ko-unit-18', '혀',       'tongue',       'hyeo'),
  V('ko-unit-18', '목',       'neck / throat', 'mok'),
  V('ko-unit-18', '어깨',     'shoulder',     'eokkae'),
  V('ko-unit-18', '팔',       'arm',          'pal'),
  V('ko-unit-18', '손',       'hand',         'son'),
  V('ko-unit-18', '손가락',   'finger',       'songarak'),
  V('ko-unit-18', '손톱',     'fingernail',   'sontop'),
  V('ko-unit-18', '가슴',     'chest / heart', 'gaseum'),
  V('ko-unit-18', '배',       'stomach / belly', 'bae'),
  V('ko-unit-18', '등',       'back',         'deung'),
  V('ko-unit-18', '허리',     'waist / lower back', 'heori'),
  V('ko-unit-18', '엉덩이',   'buttocks / hips', 'eongdeongi'),
  V('ko-unit-18', '다리',     'leg / bridge', 'dari', { note: 'Same word for leg and bridge.' }),
  V('ko-unit-18', '무릎',     'knee',         'mureup'),
  V('ko-unit-18', '발',       'foot',         'bal'),
  V('ko-unit-18', '발가락',   'toe',          'balgarak'),
  V('ko-unit-18', '피부',     'skin',         'pibu'),
  V('ko-unit-18', '뼈',       'bone',         'ppyeo'),
  V('ko-unit-18', '근육',     'muscle',       'geunyuk'),
  V('ko-unit-18', '피',       'blood',        'pi'),
  V('ko-unit-18', '심장',     'heart (organ)','simjang'),
  V('ko-unit-18', '폐',       'lungs',        'pye'),
  V('ko-unit-18', '간',       'liver',        'gan'),
  V('ko-unit-18', '위',       'stomach (organ)', 'wi'),
  V('ko-unit-18', '뇌',       'brain',        'noe'),

  // ── Unit 19: Colors & Descriptions ──────────────────────────────────────────
  V('ko-unit-19', '색',       'color',        'saek'),
  V('ko-unit-19', '빨간색',   'red',          'ppalgansaek'),
  V('ko-unit-19', '파란색',   'blue',         'paransaek'),
  V('ko-unit-19', '노란색',   'yellow',       'noransaek'),
  V('ko-unit-19', '초록색',   'green',        'choroksaek'),
  V('ko-unit-19', '주황색',   'orange',       'juhwangsaek'),
  V('ko-unit-19', '보라색',   'purple',       'borasaek'),
  V('ko-unit-19', '분홍색',   'pink',         'bunhongsaek'),
  V('ko-unit-19', '갈색',     'brown',        'galsaek'),
  V('ko-unit-19', '회색',     'gray',         'hoesaek'),
  V('ko-unit-19', '검정색',   'black',        'geomjeongsaek'),
  V('ko-unit-19', '하얀색',   'white',        'hayansaek'),
  V('ko-unit-19', '하늘색',   'sky blue',     'haneulsaek'),
  V('ko-unit-19', '금색',     'gold',         'geumsaek'),
  V('ko-unit-19', '은색',     'silver',       'eunsaek'),
  V('ko-unit-19', '연한',     'light (in color)', 'yeonhan', { pos: 'modifier' }),
  V('ko-unit-19', '진한',     'dark (in color)',  'jinhan',  { pos: 'modifier' }),
  V('ko-unit-19', '밝다',     'to be bright', 'bakda', { pos: 'adjective' }),
  V('ko-unit-19', '어둡다',   'to be dark',   'eodupda', { pos: 'adjective' }),
  V('ko-unit-19', '둥글다',   'to be round',  'dunggeulda', { pos: 'adjective' }),
  V('ko-unit-19', '네모',     'square',       'nemo'),
  V('ko-unit-19', '세모',     'triangle',     'semo'),
  V('ko-unit-19', '동그라미', 'circle',       'donggeurami'),

  // ── Unit 20: Clothing & Appearance ──────────────────────────────────────────
  V('ko-unit-20', '옷',       'clothes',          'ot'),
  V('ko-unit-20', '셔츠',     'shirt',            'syeocheu'),
  V('ko-unit-20', '티셔츠',   't-shirt',          'tisyeocheu'),
  V('ko-unit-20', '바지',     'pants / trousers', 'baji'),
  V('ko-unit-20', '청바지',   'jeans',            'cheongbaji'),
  V('ko-unit-20', '치마',     'skirt',            'chima'),
  V('ko-unit-20', '원피스',   'dress',            'wonpiseu'),
  V('ko-unit-20', '재킷',     'jacket',           'jaekit'),
  V('ko-unit-20', '코트',     'coat',             'koteu'),
  V('ko-unit-20', '스웨터',   'sweater',          'seuweteo'),
  V('ko-unit-20', '양말',     'socks',            'yangmal'),
  V('ko-unit-20', '신발',     'shoes',            'sinbal'),
  V('ko-unit-20', '운동화',   'sneakers',         'undonghwa'),
  V('ko-unit-20', '구두',     'dress shoes',      'gudu'),
  V('ko-unit-20', '모자',     'hat',              'moja'),
  V('ko-unit-20', '안경',     'glasses',          'angyeong'),
  V('ko-unit-20', '시계',     'watch / clock',    'sigye'),
  V('ko-unit-20', '가방',     'bag',              'gabang'),
  V('ko-unit-20', '지갑',     'wallet',           'jigap'),
  V('ko-unit-20', '목걸이',   'necklace',         'mokgeori'),
  V('ko-unit-20', '귀걸이',   'earring',          'gwigeori'),
  V('ko-unit-20', '반지',     'ring',             'banji'),
  V('ko-unit-20', '화장',     'makeup',           'hwajang', { note: 'K-beauty is a global industry. 화장하다 = "to put on makeup".' }),
  V('ko-unit-20', '향수',     'perfume',          'hyangsu'),
  V('ko-unit-20', '머리카락', 'hair (strand)',    'meorikarak'),

  // ── Unit 22: Animals ────────────────────────────────────────────────────────
  V('ko-unit-22', '동물',   'animal',         'dongmul'),
  V('ko-unit-22', '개',     'dog',            'gae'),
  V('ko-unit-22', '강아지', 'puppy',          'gangaji'),
  V('ko-unit-22', '고양이', 'cat',            'goyangi'),
  V('ko-unit-22', '말',     'horse / speech', 'mal', { note: 'Two meanings: horse, or "speech/words". 한국말 = "Korean (language)".' }),
  V('ko-unit-22', '소',     'cow',            'so'),
  V('ko-unit-22', '돼지',   'pig',            'dwaeji'),
  V('ko-unit-22', '닭',     'chicken',        'dak'),
  V('ko-unit-22', '오리',   'duck',           'ori'),
  V('ko-unit-22', '양',     'sheep',          'yang'),
  V('ko-unit-22', '토끼',   'rabbit',         'tokki'),
  V('ko-unit-22', '쥐',     'mouse / rat',    'jwi'),
  V('ko-unit-22', '곰',     'bear',           'gom', { note: 'The 단군 founding myth has a bear becoming the first Korean woman after eating garlic and mugwort in a cave for 100 days.' }),
  V('ko-unit-22', '호랑이', 'tiger',          'horangi', { note: 'A traditional symbol of Korea, central to folklore and art.' }),
  V('ko-unit-22', '사자',   'lion',           'saja'),
  V('ko-unit-22', '코끼리', 'elephant',       'kokkiri'),
  V('ko-unit-22', '원숭이', 'monkey',         'wonsungi'),
  V('ko-unit-22', '여우',   'fox',            'yeou', { note: 'Featured in folktales as a clever, sometimes mischievous creature.' }),
  V('ko-unit-22', '늑대',   'wolf',           'neukdae'),
  V('ko-unit-22', '뱀',     'snake',          'baem'),
  V('ko-unit-22', '거북이', 'turtle',         'geobugi'),
  V('ko-unit-22', '개구리', 'frog',           'gaeguri'),
  V('ko-unit-22', '물고기', 'fish (animal)',  'mulgogi'),
  V('ko-unit-22', '새',     'bird',           'sae'),
  V('ko-unit-22', '까치',   'magpie',         'kkachi', { note: 'In folklore, a magpie\'s call announces a welcome visitor.' }),
  V('ko-unit-22', '까마귀', 'crow / raven',   'kkamagwi'),
  V('ko-unit-22', '독수리', 'eagle',          'doksuri'),
  V('ko-unit-22', '벌',     'bee',            'beol'),
  V('ko-unit-22', '나비',   'butterfly',      'nabi'),
  V('ko-unit-22', '모기',   'mosquito',       'mogi'),

  // ── Unit 23: Weather & Environment ──────────────────────────────────────────
  V('ko-unit-23', '날씨',     'weather',         'nalssi'),
  V('ko-unit-23', '비',       'rain',            'bi'),
  V('ko-unit-23', '눈',       'snow',            'nun'),
  V('ko-unit-23', '바람',     'wind',            'baram'),
  V('ko-unit-23', '구름',     'cloud',           'gureum'),
  V('ko-unit-23', '안개',     'fog',             'angae'),
  V('ko-unit-23', '천둥',     'thunder',         'cheondung'),
  V('ko-unit-23', '번개',     'lightning',       'beongae'),
  V('ko-unit-23', '태풍',     'typhoon',         'taepung', { note: 'Korea is hit by 2-3 typhoons per year, mostly in late summer.' }),
  V('ko-unit-23', '장마',     'monsoon / rainy season', 'jangma', { note: 'The summer rainy season (late June to late July) — high humidity, frequent storms.' }),
  V('ko-unit-23', '황사',     'yellow dust',     'hwangsa', { note: 'Spring dust storms from the Gobi Desert in China — a major air-quality and health issue.' }),
  V('ko-unit-23', '미세먼지', 'fine dust / smog', 'misemeonji', { note: 'Air pollution is a daily concern; masks and air quality apps are routine.' }),
  V('ko-unit-23', '햇빛',     'sunshine',        'haetbit'),
  V('ko-unit-23', '햇볕',     'sunshine (warming)', 'haetbyeot'),
  V('ko-unit-23', '하늘',     'sky',             'haneul'),
  V('ko-unit-23', '땅',       'ground / land',   'ttang'),
  V('ko-unit-23', '바다',     'sea / ocean',     'bada'),
  V('ko-unit-23', '강',       'river',           'gang'),
  V('ko-unit-23', '호수',     'lake',            'hosu'),
  V('ko-unit-23', '산',       'mountain',        'san', { note: '70% of Korea is mountainous. Hiking is a national pastime.' }),
  V('ko-unit-23', '숲',       'forest',          'sup'),
  V('ko-unit-23', '나무',     'tree',            'namu'),
  V('ko-unit-23', '꽃',       'flower',          'kkot'),
  V('ko-unit-23', '벚꽃',     'cherry blossom',  'beotkkot', { note: 'Spring cherry blossoms (벚꽃 축제) draw huge crowds; festivals across the country in late March/April.' }),
  V('ko-unit-23', '단풍',     'autumn leaves',   'danpung', { note: 'Korean autumn foliage is brilliant; "단풍놀이" (leaf-viewing) is a major outing.' }),
  V('ko-unit-23', '잔디',     'grass',           'janli'),
  V('ko-unit-23', '돌',       'stone',           'dol'),
  V('ko-unit-23', '환경',     'environment',     'hwangyeong'),
  V('ko-unit-23', '오염',     'pollution',       'oyeom'),
  V('ko-unit-23', '재활용',   'recycling',       'jaehwaryong', { note: 'Korea has strict, color-coded recycling; sorting waste correctly is a civic ritual.' }),

  // ── Unit 24: Technology & Modern Life ───────────────────────────────────────
  V('ko-unit-24', '핸드폰',   'mobile phone',    'haendeupon'),
  V('ko-unit-24', '휴대폰',   'cell phone',      'hyudaepon'),
  V('ko-unit-24', '스마트폰', 'smartphone',      'seumateupon'),
  V('ko-unit-24', '컴퓨터',   'computer',        'kompyuteo'),
  V('ko-unit-24', '노트북',   'laptop',          'noteubuk'),
  V('ko-unit-24', '인터넷',   'internet',        'inteonet'),
  V('ko-unit-24', '와이파이', 'WiFi',            'waipai'),
  V('ko-unit-24', '이메일',   'email',           'imeil'),
  V('ko-unit-24', '문자',     'text message',    'munja'),
  V('ko-unit-24', '카톡',     'KakaoTalk message', 'katok', { note: 'KakaoTalk is Korea\'s dominant messaging app; "카톡 보내" = "send me a kakao message" is everyday speech.' }),
  V('ko-unit-24', '앱',       'app',             'aep'),
  V('ko-unit-24', '게임',     'game',            'geim'),
  V('ko-unit-24', '비밀번호', 'password',        'bimilbeonho'),
  V('ko-unit-24', '아이디',   'ID / username',   'aidi'),
  V('ko-unit-24', '검색',     'search',          'geomsaek'),
  V('ko-unit-24', '다운로드', 'download',        'daunlodeu'),
  V('ko-unit-24', '업로드',   'upload',          'eopllodeu'),
  V('ko-unit-24', '계정',     'account',         'gyejeong'),
  V('ko-unit-24', '댓글',     'comment (online)', 'daetgeul'),
  V('ko-unit-24', '좋아요',   'like (on social media)', 'joayo'),
  V('ko-unit-24', '팔로우',   'follow',          'pallou'),
  V('ko-unit-24', '구독',     'subscribe',       'gudok'),
  V('ko-unit-24', '유튜브',   'YouTube',         'yutyubeu'),
  V('ko-unit-24', '인스타',   'Instagram',       'inseuta'),
  V('ko-unit-24', '네이버',   'Naver (search engine)', 'neibeo', { note: 'Korea\'s dominant search engine and web portal — bigger than Google here.' }),
  V('ko-unit-24', '카카오',   'Kakao',           'kakao'),
  V('ko-unit-24', '충전',     'charging',        'chungjeon'),
  V('ko-unit-24', '배터리',   'battery',         'baeteori'),
  V('ko-unit-24', 'PC방',     'PC café',         'PC bang', { note: 'Gaming cafés where Koreans play together. Where competitive gaming culture (and esports) was born.' }),

  // ── Unit 25: Sports & Recreation ────────────────────────────────────────────
  V('ko-unit-25', '운동',       'exercise / sport', 'undong'),
  V('ko-unit-25', '축구',       'soccer / football', 'chukgu', { note: 'Korea\'s most popular sport — the 2002 World Cup (4th place) is national pride.' }),
  V('ko-unit-25', '야구',       'baseball',       'yagu', { note: 'Hugely popular; KBO games are a lively summer ritual.' }),
  V('ko-unit-25', '농구',       'basketball',     'nonggu'),
  V('ko-unit-25', '배구',       'volleyball',     'baegu'),
  V('ko-unit-25', '태권도',     'taekwondo',      'taegwondo', { note: 'Korea\'s national martial art and an Olympic sport.' }),
  V('ko-unit-25', '골프',       'golf',           'golpeu'),
  V('ko-unit-25', '수영',       'swimming',       'suyeong'),
  V('ko-unit-25', '등산',       'hiking / mountain climbing', 'deungsan', { note: 'A national obsession — gear-clad hikers fill every mountain on weekends.' }),
  V('ko-unit-25', '낚시',       'fishing',        'naksi'),
  V('ko-unit-25', '게임',       'video game',     'geim'),
  V('ko-unit-25', '이스포츠',   'esports',        'iseupocheu', { note: 'Korea is a global esports superpower — Starcraft and League of Legends pros are celebrities.' }),
  V('ko-unit-25', '취미',       'hobby',          'chwimi'),
  V('ko-unit-25', '스포츠',     'sports',         'seupocheu'),
  V('ko-unit-25', '경기',       'match / game',   'gyeonggi'),
  V('ko-unit-25', '선수',       'athlete / player', 'seonsu'),
  V('ko-unit-25', '팀',         'team',           'tim'),
  V('ko-unit-25', '코치',       'coach',          'kochi'),
  V('ko-unit-25', '응원',       'cheering',       'eungwon', { note: 'Group cheering at games is a coordinated art — Korean cheering culture is famously organized and loud.' }),

  // ── Unit 26: Music, Movies & Drama ──────────────────────────────────────────
  V('ko-unit-26', '음악',     'music',           'eumak'),
  V('ko-unit-26', '노래',     'song',            'norae'),
  V('ko-unit-26', '가수',     'singer',          'gasu'),
  V('ko-unit-26', '아이돌',   'idol (K-pop star)', 'aidol', { note: 'K-pop idols are trained for years before debut and follow strict performance + image expectations.' }),
  V('ko-unit-26', '걸그룹',   'girl group',      'geolgeurup'),
  V('ko-unit-26', '보이그룹', 'boy group',       'boigeurup'),
  V('ko-unit-26', '팬',       'fan',             'paen'),
  V('ko-unit-26', '팬덤',     'fandom',          'paendeom', { note: 'Korean fandoms are highly organized — each group has a name (e.g. ARMY for BTS) and coordinated activities.' }),
  V('ko-unit-26', '콘서트',   'concert',         'konseoteu'),
  V('ko-unit-26', '앨범',     'album',           'aelbeom'),
  V('ko-unit-26', '뮤직비디오', 'music video',   'myujikbidio'),
  V('ko-unit-26', '안무',     'choreography',    'anmu'),
  V('ko-unit-26', '영화',     'movie',           'yeonghwa'),
  V('ko-unit-26', '드라마',   'TV drama',        'deurama', { note: 'K-dramas are a global phenomenon — typically 16-20 episodes, with a beginning/middle/end (unlike US shows).' }),
  V('ko-unit-26', '예능',     'variety show',    'yeneung', { note: 'Korean variety shows are a major TV genre — celebrities playing games, eating, traveling.' }),
  V('ko-unit-26', '배우',     'actor',           'baeu'),
  V('ko-unit-26', '감독',     'director',        'gamdok'),
  V('ko-unit-26', '주인공',   'main character',  'juingong'),
  V('ko-unit-26', '연기',     'acting',          'yeongi'),
  V('ko-unit-26', '시즌',     'season (of show)', 'sijeun'),

  // ── Unit 27: Education & School ─────────────────────────────────────────────
  V('ko-unit-27', '학생',       'student',          'haksaeng'),
  V('ko-unit-27', '선생님',     'teacher',          'seonsaengnim', { note: '님 is an honorific suffix; teachers are addressed with high respect.' }),
  V('ko-unit-27', '교수',       'professor',        'gyosu'),
  V('ko-unit-27', '교실',       'classroom',        'gyosil'),
  V('ko-unit-27', '수업',       'class / lesson',   'sueop'),
  V('ko-unit-27', '숙제',       'homework',         'sukje'),
  V('ko-unit-27', '시험',       'exam',             'siheom'),
  V('ko-unit-27', '수능',       'university entrance exam', 'suneung', { note: 'The notoriously high-stakes university entrance exam, taken nationwide on a single day in November. Planes are grounded during the listening test.' }),
  V('ko-unit-27', '점수',       'score',            'jeomsu'),
  V('ko-unit-27', '책',         'book',             'chaek'),
  V('ko-unit-27', '연필',       'pencil',           'yeonpil'),
  V('ko-unit-27', '볼펜',       'ballpoint pen',    'bolpen'),
  V('ko-unit-27', '공책',       'notebook',         'gongchaek'),
  V('ko-unit-27', '가방',       'school bag',       'gabang'),
  V('ko-unit-27', '교과서',     'textbook',         'gyogwaseo'),
  V('ko-unit-27', '도서관',     'library',          'doseogwan'),
  V('ko-unit-27', '학원',       'cram school / academy', 'hagwon', { note: 'After-school private academies — a massive industry. Many students attend several until late at night.' }),
  V('ko-unit-27', '과외',       'private tutoring', 'gwaoe'),
  V('ko-unit-27', '졸업',       'graduation',       'joreop'),
  V('ko-unit-27', '입학',       'entering school',  'iphak'),
  V('ko-unit-27', '전공',       'major',            'jeongong'),
  V('ko-unit-27', '학년',       'grade / year (in school)', 'hangnyeon'),
  V('ko-unit-27', '동아리',     'club / circle',    'dongari', { note: 'Korean university clubs — strong bonds, shared meals, hierarchical seniority.' }),
  V('ko-unit-27', '학교',       'school',           'hakgyo'),
  V('ko-unit-27', '초등학교',   'elementary school', 'chodeunghakgyo'),
  V('ko-unit-27', '중학교',     'middle school',    'junghakgyo'),
  V('ko-unit-27', '고등학교',   'high school',      'godeunghakgyo'),

  // ── Unit 28: Work & Office Life ─────────────────────────────────────────────
  V('ko-unit-28', '직장',     'workplace',        'jikjang'),
  V('ko-unit-28', '직업',     'job / occupation', 'jigeop'),
  V('ko-unit-28', '회의',     'meeting',          'hoeui'),
  V('ko-unit-28', '월급',     'monthly salary',   'wolgeup'),
  V('ko-unit-28', '연봉',     'annual salary',    'yeonbong'),
  V('ko-unit-28', '보너스',   'bonus',            'boneoseu'),
  V('ko-unit-28', '휴가',     'vacation / leave', 'hyuga'),
  V('ko-unit-28', '야근',     'overtime work',    'yageun', { note: 'A persistent feature of Korean work culture — staying late is often expected, though norms are shifting.' }),
  V('ko-unit-28', '출근',     'going to work',    'chulgeun'),
  V('ko-unit-28', '퇴근',     'leaving work',     'toegeun'),
  V('ko-unit-28', '사장님',   'boss / CEO',       'sajangnim'),
  V('ko-unit-28', '부장',     'manager / dept head', 'bujang'),
  V('ko-unit-28', '과장',     'section chief',    'gwajang'),
  V('ko-unit-28', '대리',     'assistant manager', 'daeri'),
  V('ko-unit-28', '신입',     'new employee / rookie', 'sinip'),
  V('ko-unit-28', '동료',     'colleague',        'dongnyo'),
  V('ko-unit-28', '면접',     'interview',        'myeonjeop'),
  V('ko-unit-28', '이력서',   'résumé',           'iryeokseo'),
  V('ko-unit-28', '계약',     'contract',         'gyeyak'),
  V('ko-unit-28', '프로젝트', 'project',          'peurojekteu'),
  V('ko-unit-28', '명함',     'business card',    'myeongham', { note: 'Exchanged with two hands and treated with respect — never shoved in a pocket.' }),
  V('ko-unit-28', '비즈니스', 'business',         'bijeuniseu'),

  // ── Unit 29: Emotions ───────────────────────────────────────────────────────
  V('ko-unit-29', '기분',     'mood / feeling',  'gibun'),
  V('ko-unit-29', '감정',     'emotion',         'gamjeong'),
  V('ko-unit-29', '행복',     'happiness',       'haengbok'),
  V('ko-unit-29', '슬픔',     'sadness',         'seulpeum'),
  V('ko-unit-29', '기쁨',     'joy',             'gippeum'),
  V('ko-unit-29', '분노',     'anger',           'bunno'),
  V('ko-unit-29', '두려움',   'fear',            'duryeoum'),
  V('ko-unit-29', '놀라움',   'surprise',        'nollaum'),
  V('ko-unit-29', '외로움',   'loneliness',      'oeroum'),
  V('ko-unit-29', '그리움',   'longing / missing someone', 'geurium', { tags: ['culture'],
    note: 'The bittersweet feeling of missing someone or a place — a recurrent theme in Korean songs and literature.' }),
  V('ko-unit-29', '설렘',     'butterflies / fluttering excitement', 'seollem', { tags: ['culture'],
    note: 'The fluttery feeling at the start of love, or before something exciting. Untranslatable in one word.' }),
  V('ko-unit-29', '부끄러움', 'embarrassment',   'bukkeureoum'),
  V('ko-unit-29', '자랑',     'pride / boast',   'jarang'),
  V('ko-unit-29', '질투',     'jealousy',        'jiltu'),
  V('ko-unit-29', '사랑',     'love',            'sarang'),
  V('ko-unit-29', '미움',     'hatred',          'mium'),
  V('ko-unit-29', '존경',     'respect',         'jongyeong'),
  V('ko-unit-29', '신뢰',     'trust',           'silloe'),
  V('ko-unit-29', '실망',     'disappointment',  'silmang'),
  V('ko-unit-29', '희망',     'hope',            'huimang'),
  V('ko-unit-29', '용기',     'courage',         'yonggi'),
  V('ko-unit-29', '걱정',     'worry',           'geokjeong'),
  V('ko-unit-29', '스트레스', 'stress',          'seuteureseu'),

  // ── Unit 30: Abstract Nouns ─────────────────────────────────────────────────
  V('ko-unit-30', '진실',   'truth',          'jinsil'),
  V('ko-unit-30', '거짓말', 'lie',            'geojinmal'),
  V('ko-unit-30', '비밀',   'secret',         'bimil'),
  V('ko-unit-30', '약속',   'promise',        'yaksok'),
  V('ko-unit-30', '자유',   'freedom',        'jayu'),
  V('ko-unit-30', '평화',   'peace',          'pyeonghwa'),
  V('ko-unit-30', '전쟁',   'war',            'jeonjaeng'),
  V('ko-unit-30', '정의',   'justice',        'jeongui'),
  V('ko-unit-30', '권리',   'right (legal)',  'gwolli'),
  V('ko-unit-30', '의무',   'duty',           'uimu'),
  V('ko-unit-30', '문화',   'culture',        'munhwa'),
  V('ko-unit-30', '역사',   'history',        'yeoksa'),
  V('ko-unit-30', '미래',   'future',         'mirae'),
  V('ko-unit-30', '과거',   'past',           'gwageo'),
  V('ko-unit-30', '현재',   'present',        'hyeonjae'),
  V('ko-unit-30', '인생',   'life',           'insaeng'),
  V('ko-unit-30', '운명',   'fate',           'unmyeong'),
  V('ko-unit-30', '꿈',     'dream',          'kkum'),
  V('ko-unit-30', '목표',   'goal',           'mokpyo'),
  V('ko-unit-30', '성공',   'success',        'seonggong'),
  V('ko-unit-30', '실패',   'failure',        'silpae'),
  V('ko-unit-30', '경험',   'experience',     'gyeongheom'),
  V('ko-unit-30', '기회',   'opportunity',    'gihoe'),
  V('ko-unit-30', '능력',   'ability',        'neungnyeok'),
  V('ko-unit-30', '지혜',   'wisdom',         'jihye'),
  V('ko-unit-30', '지식',   'knowledge',      'jisik'),
  V('ko-unit-30', '생각',   'thought',        'saenggak'),
  V('ko-unit-30', '의견',   'opinion',        'uigyeon'),
  V('ko-unit-30', '관계',   'relationship',   'gwangye'),

  // ── Unit 31: Adverbs & Connectors ───────────────────────────────────────────
  V('ko-unit-31', '아주',     'very',            'aju',     { pos: 'adverb' }),
  V('ko-unit-31', '너무',     'too / very',      'neomu',   { pos: 'adverb' }),
  V('ko-unit-31', '정말',     'really',          'jeongmal', { pos: 'adverb' }),
  V('ko-unit-31', '진짜',     'truly / really',  'jinjja',  { pos: 'adverb' }),
  V('ko-unit-31', '조금',     'a little',        'jogeum',  { pos: 'adverb' }),
  V('ko-unit-31', '많이',     'a lot',           'mani',    { pos: 'adverb' }),
  V('ko-unit-31', '잘',       'well',            'jal',     { pos: 'adverb' }),
  V('ko-unit-31', '잘못',     'wrongly / by mistake', 'jalmot', { pos: 'adverb' }),
  V('ko-unit-31', '빨리',     'quickly',         'ppalli',  { pos: 'adverb' }),
  V('ko-unit-31', '천천히',   'slowly',          'cheoncheonhi', { pos: 'adverb' }),
  V('ko-unit-31', '아직',     'still / not yet', 'ajik',    { pos: 'adverb' }),
  V('ko-unit-31', '벌써',     'already',         'beolsseo', { pos: 'adverb' }),
  V('ko-unit-31', '곧',       'soon',            'got',     { pos: 'adverb' }),
  V('ko-unit-31', '항상',     'always',          'hangsang', { pos: 'adverb' }),
  V('ko-unit-31', '자주',     'often',           'jaju',    { pos: 'adverb' }),
  V('ko-unit-31', '가끔',     'sometimes',       'gakkeum', { pos: 'adverb' }),
  V('ko-unit-31', '절대',     'absolutely (with negative)', 'jeoldae', { pos: 'adverb' }),
  V('ko-unit-31', '특히',     'especially',      'teukhi',  { pos: 'adverb' }),
  V('ko-unit-31', '그래서',   'so / therefore',  'geuraeseo', { pos: 'conjunction' }),
  V('ko-unit-31', '그런데',   'but / however',   'geureonde', { pos: 'conjunction' }),
  V('ko-unit-31', '그리고',   'and',             'geurigo', { pos: 'conjunction' }),
  V('ko-unit-31', '하지만',   'but',             'hajiman', { pos: 'conjunction' }),
  V('ko-unit-31', '그러면',   'then / in that case', 'geureomyeon', { pos: 'conjunction' }),
  V('ko-unit-31', '왜냐하면', 'because',         'waenyahamyeon', { pos: 'conjunction' }),
  V('ko-unit-31', '또',       'again / also',    'tto',     { pos: 'adverb' }),
  V('ko-unit-31', '먼저',     'first',           'meonjeo', { pos: 'adverb' }),
  V('ko-unit-31', '마지막',   'last',            'majimak'),
  V('ko-unit-31', '결국',     'in the end / eventually', 'gyeolguk', { pos: 'adverb' }),

  // ── Unit 32: House & Home ───────────────────────────────────────────────────
  V('ko-unit-32', '아파트',   'apartment',          'apateu', { note: 'Most Koreans live in apartment buildings — high-density living is the urban default.' }),
  V('ko-unit-32', '방',       'room',               'bang'),
  V('ko-unit-32', '거실',     'living room',        'geosil'),
  V('ko-unit-32', '부엌',     'kitchen',            'bueok'),
  V('ko-unit-32', '주방',     'kitchen',            'jubang'),
  V('ko-unit-32', '침실',     'bedroom',            'chimsil'),
  V('ko-unit-32', '화장실',   'bathroom',           'hwajangsil'),
  V('ko-unit-32', '베란다',   'balcony',            'beranda'),
  V('ko-unit-32', '문',       'door',               'mun'),
  V('ko-unit-32', '창문',     'window',             'changmun'),
  V('ko-unit-32', '벽',       'wall',               'byeok'),
  V('ko-unit-32', '바닥',     'floor',              'badak'),
  V('ko-unit-32', '천장',     'ceiling',            'cheonjang'),
  V('ko-unit-32', '계단',     'stairs',             'gyedan'),
  V('ko-unit-32', '엘리베이터', 'elevator',         'ellibeiteo'),
  V('ko-unit-32', '온돌',     'floor heating',      'ondol', { note: 'Traditional Korean underfloor heating. Why Koreans take shoes off at the door and sit on the floor.' }),
  V('ko-unit-32', '소파',     'sofa',               'sopa'),
  V('ko-unit-32', '의자',     'chair',              'uija'),
  V('ko-unit-32', '책상',     'desk',               'chaeksang'),
  V('ko-unit-32', '식탁',     'dining table',       'siktak'),
  V('ko-unit-32', '침대',     'bed',                'chimdae'),
  V('ko-unit-32', '이불',     'blanket / bedding',  'ibul'),
  V('ko-unit-32', '베개',     'pillow',             'begae'),
  V('ko-unit-32', '냉장고',   'refrigerator',       'naengjanggo'),
  V('ko-unit-32', '김치냉장고', 'kimchi refrigerator', 'gimchinaengjanggo',
    { note: 'A second fridge dedicated to kimchi — found in most Korean homes.' }),
  V('ko-unit-32', '세탁기',   'washing machine',    'setakgi'),
  V('ko-unit-32', '청소기',   'vacuum cleaner',     'cheongsogi'),
  V('ko-unit-32', '전등',     'lamp / light',       'jeondeung'),
  V('ko-unit-32', '거울',     'mirror',             'geoul'),

  // ── Unit 33: Nature ─────────────────────────────────────────────────────────
  V('ko-unit-33', '자연',     'nature',             'jayeon'),
  V('ko-unit-33', '바위',     'rock / boulder',     'bawi'),
  V('ko-unit-33', '계곡',     'valley',             'gyegok'),
  V('ko-unit-33', '폭포',     'waterfall',          'pokpo'),
  V('ko-unit-33', '섬',       'island',             'seom'),
  V('ko-unit-33', '해변',     'beach',              'haebyeon'),
  V('ko-unit-33', '동굴',     'cave',               'donggul'),
  V('ko-unit-33', '들판',     'field / plain',      'deulpan'),
  V('ko-unit-33', '논',       'rice paddy',         'non'),
  V('ko-unit-33', '밭',       'dry field',          'bat'),
  V('ko-unit-33', '별',       'star',               'byeol'),
  V('ko-unit-33', '달',       'moon',               'dal'),
  V('ko-unit-33', '해',       'sun',                'hae'),
  V('ko-unit-33', '우주',     'universe',           'uju'),
  V('ko-unit-33', '지구',     'Earth',              'jigu'),
  V('ko-unit-33', '세계',     'world',              'segye'),
  V('ko-unit-33', '나라',     'country',            'nara'),
  V('ko-unit-33', '한라산',   'Mt. Halla (Jeju)',   'hallasan', { note: 'South Korea\'s highest peak (1,947m), on Jeju Island.' }),
  V('ko-unit-33', '백두산',   'Mt. Baekdu',         'baekdusan', { note: 'The mythological birthplace of the Korean people, on the China–North Korea border.' }),
  V('ko-unit-33', '동해',     'East Sea',           'donghae'),
  V('ko-unit-33', '서해',     'West Sea / Yellow Sea', 'seohae'),
  V('ko-unit-33', '남해',     'South Sea',          'namhae'),

  // ── Unit 34: Religion & Spirituality ────────────────────────────────────────
  V('ko-unit-34', '종교',     'religion',           'jonggyo'),
  V('ko-unit-34', '불교',     'Buddhism',           'bulgyo', { note: 'Buddhism shaped Korean art, philosophy, and culture for over 1,500 years.' }),
  V('ko-unit-34', '기독교',   'Christianity',       'gidokgyo', { note: 'Christianity (esp. Protestantism) has grown rapidly since the 19th century; ~30% of South Koreans now identify as Christian.' }),
  V('ko-unit-34', '천주교',   'Catholicism',        'cheonjugyo'),
  V('ko-unit-34', '유교',     'Confucianism',       'yugyo', { note: 'Less a religion than a deep social philosophy that still shapes hierarchy, family, and respect in Korean life.' }),
  V('ko-unit-34', '무속',     'shamanism',          'musok', { note: 'Korea\'s indigenous shamanic tradition, with 무당 (shamans) performing rituals (굿) to communicate with spirits.' }),
  V('ko-unit-34', '하나님',   'God (Christian)',    'hananim'),
  V('ko-unit-34', '부처',     'Buddha',             'bucheo'),
  V('ko-unit-34', '예수님',   'Jesus',              'yesunim'),
  V('ko-unit-34', '스님',     'Buddhist monk',      'seunim'),
  V('ko-unit-34', '목사',     'pastor / minister',  'moksa'),
  V('ko-unit-34', '신부',     'Catholic priest',    'sinbu'),
  V('ko-unit-34', '교회',     'church',             'gyohoe'),
  V('ko-unit-34', '성당',     'Catholic cathedral', 'seongdang'),
  V('ko-unit-34', '절',       'Buddhist temple',    'jeol'),
  V('ko-unit-34', '기도',     'prayer',             'gido'),
  V('ko-unit-34', '믿음',     'faith / belief',     'mideum'),
  V('ko-unit-34', '영혼',     'soul',               'yeonghon'),
  V('ko-unit-34', '천당',     'heaven',             'cheondang'),
  V('ko-unit-34', '지옥',     'hell',               'jiok'),
  V('ko-unit-34', '명상',     'meditation',         'myeongsang'),
  V('ko-unit-34', '템플스테이', 'temple stay',      'tempeulseutei', { note: 'A program where visitors stay overnight at a Buddhist temple to experience monastic life.' }),

  // ── Unit 35: Korean Pop Culture ─────────────────────────────────────────────
  V('ko-unit-35', '한류',     'the Korean Wave',  'hallyu', { tags: ['culture'],
    note: 'The global spread of Korean entertainment — K-pop, K-dramas, films, food — since the late 1990s.' }),
  V('ko-unit-35', '먹방',     'mukbang (eating show)', 'meokbang', { tags: ['culture'],
    note: 'A genre of broadcasting where the host eats large portions on camera. Originated in Korea and went global.' }),
  V('ko-unit-35', '브이로그', 'vlog',             'beuirogeu'),
  V('ko-unit-35', '셀카',     'selfie',           'selka'),
  V('ko-unit-35', '셀럽',     'celebrity',        'selleop'),
  V('ko-unit-35', '인기',     'popularity',       'ingi'),
  V('ko-unit-35', '인기 있다', 'to be popular',    'ingi itda', { pos: 'verb' }),
  V('ko-unit-35', '데뷔',     'debut',            'debwi'),
  V('ko-unit-35', '컴백',     'comeback (new release)', 'keombaek', { tags: ['culture'],
    note: 'A K-pop "comeback" = a new release/promotion cycle, not a return after a long break.' }),
  V('ko-unit-35', '굿즈',     'merchandise (goods)', 'gutjeu'),
  V('ko-unit-35', '오빠 부대', "oppa squad (fan base)", 'oppa budae', { tags: ['culture'] }),
  V('ko-unit-35', '덕질',     'fandom activity / stanning', 'deokjil', { tags: ['culture'],
    note: 'The act of being a passionate fan — collecting merch, attending events, supporting an idol.' }),
  V('ko-unit-35', '입덕',     'becoming a fan',   'ipdeok', { tags: ['culture'] }),
  V('ko-unit-35', '탈덕',     'leaving a fandom', 'taldeok', { tags: ['culture'] }),
  V('ko-unit-35', '연예인',   'entertainer / celebrity', 'yeonyein'),
  V('ko-unit-35', '소속사',   'agency / management', 'sosoksa', { note: 'K-pop entertainment agencies (소속사) like SM, JYP, HYBE manage idols\' careers, training, and image.' }),
  V('ko-unit-35', '인스타그램', 'Instagram',       'inseutageuraem'),
  V('ko-unit-35', '소셜미디어', 'social media',    'sosyeolmidieo'),
  V('ko-unit-35', '인플루언서', 'influencer',     'inpeulluonseo'),
  V('ko-unit-35', 'K-팝',     'K-pop',            'K-pap'),
  V('ko-unit-35', 'K-드라마', 'K-drama',          'K-deurama'),

  // ── Unit 36: Idioms & Proverbs ──────────────────────────────────────────────
  V('ko-unit-36', '속담',     'proverb',           'sokdam'),
  V('ko-unit-36', '관용어',   'idiom',             'gwanyongeo'),
  P('ko-unit-36', '시작이 반이다', 'starting is half (the battle)', 'sijagi banida',
    { tags: ['culture'], note: 'A classic motivational proverb — the hardest part is to begin.' }),
  P('ko-unit-36', '천리 길도 한 걸음부터', 'a 1,000-li journey starts with one step', 'cheolli gildo han georeumbuteo',
    { tags: ['culture'], note: 'Korean version of "a journey of a thousand miles begins with a single step".' }),
  P('ko-unit-36', '호랑이도 제 말 하면 온다', 'speak of the tiger and it appears', 'horangido je mal hamyeon onda',
    { tags: ['culture'], note: 'Korean equivalent of "speak of the devil". The tiger replaces the devil in Korean folklore.' }),
  P('ko-unit-36', '낮말은 새가 듣고 밤말은 쥐가 듣는다', 'day words birds hear, night words mice hear', 'nanmareun saega deutgo bammareun jwiga deutneunda',
    { tags: ['culture'], note: 'Walls have ears — be careful what you say, anywhere.' }),
  P('ko-unit-36', '개천에서 용 난다', 'a dragon rises from a stream', 'gaecheoneseo yong nanda',
    { tags: ['culture'], note: 'A poor background can produce great success — the "rags to riches" proverb.' }),
  P('ko-unit-36', '발 없는 말이 천리 간다', 'a footless horse / word travels 1,000 li', 'bal eomneun mari cheolli ganda',
    { tags: ['culture'], note: 'Plays on 말 (horse/word): a rumour spreads far and fast.' }),
  P('ko-unit-36', '식은 죽 먹기', "eating cold porridge", 'sigeun juk meokgi',
    { tags: ['culture'], note: 'A piece of cake — something effortless. (식은 죽 = cold porridge.)' }),
  P('ko-unit-36', '눈에서 멀어지면 마음에서도 멀어진다', "out of sight, out of mind", 'nuneseo meoreojimyeon maeumeseodo meoreojinda',
    { tags: ['culture'] }),
  P('ko-unit-36', '가는 말이 고와야 오는 말이 곱다', 'kind words going out, kind words coming back', 'ganeun mari gowaya oneun mari gopda',
    { tags: ['culture'], note: 'Treat others how you want to be treated.' }),
  P('ko-unit-36', '백문이 불여일견', 'hearing 100 times is not as good as seeing once', 'baengmuni buryeoilgyeon',
    { tags: ['culture'], note: 'Seeing is believing — Sino-Korean idiom.' }),
  P('ko-unit-36', '윗물이 맑아야 아랫물이 맑다', 'the upstream must be clear for downstream to be clear', 'witmuri malgaya araenmuri malkda',
    { tags: ['culture'], note: 'Leaders set the example; superiors must be honest for subordinates to be honest.' }),

  // ── Unit 37: Politics & Society ─────────────────────────────────────────────
  V('ko-unit-37', '정치',     'politics',          'jeongchi'),
  V('ko-unit-37', '정부',     'government',        'jeongbu'),
  V('ko-unit-37', '대통령',   'president',         'daetongnyeong'),
  V('ko-unit-37', '국회',     'National Assembly', 'gukhoe'),
  V('ko-unit-37', '국회의원', 'lawmaker',          'gukhoeuiwon'),
  V('ko-unit-37', '선거',     'election',          'seongeo'),
  V('ko-unit-37', '투표',     'vote',              'tupyo'),
  V('ko-unit-37', '정당',     'political party',   'jeongdang'),
  V('ko-unit-37', '법',       'law',               'beop'),
  V('ko-unit-37', '경찰',     'police',            'gyeongchal'),
  V('ko-unit-37', '군대',     'army / military',   'gundae', { note: 'Mandatory military service (~18 months) for South Korean men — a defining shared experience.' }),
  V('ko-unit-37', '병역',     'military service',  'byeongyeok'),
  V('ko-unit-37', '시민',     'citizen',           'simin'),
  V('ko-unit-37', '국민',     'the people / nation', 'gungmin'),
  V('ko-unit-37', '사회',     'society',           'sahoe'),
  V('ko-unit-37', '경제',     'economy',           'gyeongje'),
  V('ko-unit-37', '뉴스',     'news',              'nyuseu'),
  V('ko-unit-37', '신문',     'newspaper',         'sinmun'),
  V('ko-unit-37', '기자',     'journalist',        'gija'),
  V('ko-unit-37', '시위',     'protest / demonstration', 'siwi', { note: 'Mass candlelight protests (촛불시위) have shaped Korean political history — most famously in 2016-17.' }),

  // ── Unit 38: Business & Finance ─────────────────────────────────────────────
  V('ko-unit-38', '은행',     'bank',              'eunhaeng'),
  V('ko-unit-38', '계좌',     'bank account',      'gyejwa'),
  V('ko-unit-38', '예금',     'savings deposit',   'yegeum'),
  V('ko-unit-38', '대출',     'loan',              'daechul'),
  V('ko-unit-38', '이자',     'interest (financial)', 'ija'),
  V('ko-unit-38', '주식',     'stock',             'jusik'),
  V('ko-unit-38', '투자',     'investment',        'tuja'),
  V('ko-unit-38', '세금',     'tax',               'segeum'),
  V('ko-unit-38', '월세',     'monthly rent',      'wolse'),
  V('ko-unit-38', '전세',     'jeonse (large deposit, no rent)', 'jeonse', { note: 'A uniquely Korean rental: huge lump-sum deposit, no monthly rent, returned at end of lease.' }),
  V('ko-unit-38', '집세',     'housing rent',      'jipse'),
  V('ko-unit-38', '경기',     'economic conditions', 'gyeonggi'),
  V('ko-unit-38', '재벌',     'chaebol (family conglomerate)', 'jaebeol', { tags: ['culture'],
    note: 'Family-run conglomerates (Samsung, Hyundai, LG, SK) that dominate the Korean economy.' }),
  V('ko-unit-38', '회사',     'company',           'hoesa'),
  V('ko-unit-38', '대기업',   'large corporation', 'daegieop'),
  V('ko-unit-38', '중소기업', 'small/medium business', 'jungsogieop'),
  V('ko-unit-38', '창업',     'starting a business / startup', 'changeop'),
  V('ko-unit-38', '실업',     'unemployment',      'sireop'),
  V('ko-unit-38', '취업',     'getting a job',     'chwieop'),

  // ── Unit 39: Communication & Media ──────────────────────────────────────────
  V('ko-unit-39', '방송',     'broadcast',         'bangsong'),
  V('ko-unit-39', '라디오',   'radio',             'radio'),
  V('ko-unit-39', '텔레비전', 'television',        'tellebijeon'),
  V('ko-unit-39', 'TV',       'TV',                'TV'),
  V('ko-unit-39', '채널',     'channel',           'chaeneol'),
  V('ko-unit-39', '광고',     'advertisement',     'gwanggo'),
  V('ko-unit-39', '잡지',     'magazine',          'japji'),
  V('ko-unit-39', '책방',     'bookstore',         'chaekbang'),
  V('ko-unit-39', '글',       'writing / piece',   'geul'),
  V('ko-unit-39', '편지',     'letter',            'pyeonji'),
  V('ko-unit-39', '소설',     'novel',             'soseol'),
  V('ko-unit-39', '시',       'poem',              'si'),
  V('ko-unit-39', '에세이',   'essay',             'esei'),
  V('ko-unit-39', '인터뷰',   'interview',         'inteobyu'),
  V('ko-unit-39', '대화',     'conversation',      'daehwa'),
  V('ko-unit-39', '토론',     'discussion / debate', 'toron'),
  V('ko-unit-39', '회의',     'meeting',           'hoeui'),
  V('ko-unit-39', '발표',     'presentation / announcement', 'balpyo'),
  V('ko-unit-39', '연설',     'speech',            'yeonseol'),
  V('ko-unit-39', '강의',     'lecture',           'gangui'),

  // ── Unit 40: Discourse & Advanced Connectors ────────────────────────────────
  V('ko-unit-40', '예를 들면', 'for example',      'yereul deulmyeon', { pos: 'phrase' }),
  V('ko-unit-40', '예를 들어', 'for example',      'yereul deureo',    { pos: 'phrase' }),
  V('ko-unit-40', '즉',        'that is / namely', 'jeuk',             { pos: 'adverb' }),
  V('ko-unit-40', '말하자면',  'so to speak',      'malhajamyeon',     { pos: 'phrase' }),
  V('ko-unit-40', '한편으로',  'on the one hand',  'hanpyeoneuro',     { pos: 'phrase' }),
  V('ko-unit-40', '반면에',    'on the other hand', 'banmyeone',       { pos: 'phrase' }),
  V('ko-unit-40', '게다가',    'on top of that',   'gedaga',           { pos: 'adverb' }),
  V('ko-unit-40', '뿐만 아니라', 'not only … but also', 'ppunman anira', { pos: 'phrase' }),
  V('ko-unit-40', '그럼에도 불구하고', 'nevertheless', 'geureomedo bulguhago', { pos: 'phrase' }),
  V('ko-unit-40', '따라서',    'accordingly / hence', 'ttaraseo',      { pos: 'conjunction' }),
  V('ko-unit-40', '결과적으로', 'as a result',     'gyeolgwajeogeuro', { pos: 'phrase' }),
  V('ko-unit-40', '아무튼',    'anyway',           'amuteun',          { pos: 'adverb' }),
  V('ko-unit-40', '어쨌든',    'in any case',      'eojjaetdeun',      { pos: 'adverb' }),
  V('ko-unit-40', '한마디로',  'in a word',        'hanmadiro',        { pos: 'phrase' }),
  V('ko-unit-40', '구체적으로', 'specifically',    'guchejeogeuro',    { pos: 'adverb' }),
  V('ko-unit-40', '일반적으로', 'generally',       'ilbanjeogeuro',    { pos: 'adverb' }),
  V('ko-unit-40', '솔직히',    'frankly',          'soljikhi',         { pos: 'adverb' }),
  V('ko-unit-40', '개인적으로', 'personally',      'gaeinjeogeuro',    { pos: 'adverb' }),
];
