/**
 * Te Reo Māori vocabulary + units.
 *
 * Curriculum mirrors the Korean/Swahili shape: a core hand-curated foundation
 * that teaches everyday words PLUS the cultural concepts that make the language
 * meaningful (te ao Māori). Macrons are preserved (ā ē ī ō ū) — they mark long
 * vowels and are not optional. Pronunciation guides use a light syllable form.
 *
 * Hand-curated for quality; a native-speaker review pass should follow before
 * marketing this curriculum as polished.
 */

// Compact builders mirroring the Korean ones — V() for vocabulary, P() for phrases.
function V(unit, mi, en, pron, opts = {}) {
  return { unit, mi, en, pron, type: 'vocabulary', pos: opts.pos || 'noun', ...opts };
}
function P(unit, mi, en, pron, opts = {}) {
  return { unit, mi, en, pron, type: 'phrase', pos: 'phrase', register: opts.register || 'neutral', ...opts };
}

module.exports.UNITS = [
  // [id, name, description, level, order_index, track, grammar_notes]
  ['mi-unit-01', 'Ngā Kupu Tuatahi (First Words)', 'Greetings, courtesy, and the words you need on day one in te ao Māori.', 1, 1, 'vocabulary', ''],
  ['mi-unit-02', 'Ngā Tūmahi Pātai (Question Words)', 'Pronouns and the who / what / where / when / why of te reo.', 1, 2, 'vocabulary', ''],
  ['mi-unit-03', 'Ngā Tau (Numbers)', 'Counting from tahi to tekau and beyond — used for age, time, and price.', 1, 3, 'vocabulary', ''],
  ['mi-unit-04', 'Ngā Kīwaha (Everyday Phrases)', 'High-value sentences for getting around in te reo Māori.', 1, 4, 'vocabulary', ''],
  ['mi-unit-05', 'Te Kai (Food & Drink)', 'Food, drink, and the language of sharing a meal — manaakitanga in action.', 1, 5, 'vocabulary', ''],
  ['mi-unit-06', 'Ngā Tūmahi (Common Verbs)', 'The action words and the tense particles that mark when something happens.', 1, 6, 'vocabulary', ''],
  ['mi-unit-07', 'Te Wetereo (How Te Reo Works)', 'Tense particles, possessives, and the grammar backbone of Māori.', 1, 7, 'grammar',
    'Te reo marks tense with particles BEFORE the verb (kei te = present continuous, kua = perfective, i = past, ka = inceptive/future). Word order is verb-subject-object. Possession splits into ā- and ō-category — a meaningful distinction, not a quirk.'],
  ['mi-unit-08', 'Te Whānau (Family)', 'Whānau (family), hapū (sub-tribe), iwi (tribe) — the layered Māori sense of belonging.', 1, 8, 'vocabulary', ''],
  ['mi-unit-09', 'Te Marae me te Tikanga (Marae & Protocol)', 'The marae, the pōwhiri, and the kawa (protocol) that shape every encounter.', 2, 9, 'vocabulary', ''],
  ['mi-unit-10', 'Te Wā (Time & Days)', 'Times of day, days of the week, and talking about when.', 1, 10, 'vocabulary', ''],
  ['mi-unit-11', 'Ngā Wāhi (Places & Getting Around)', 'Houses, schools, shops, and the places of daily life.', 1, 11, 'vocabulary', ''],
  ['mi-unit-12', 'Te Ao Māori (Cultural Concepts)', 'Mana, tapu, noa, mauri, wairua — the words that carry te ao Māori.', 2, 12, 'vocabulary', ''],
  ['mi-unit-13', 'Te Tinana (Body Parts)', 'From māhunga (head) to waewae (foot) — naming the body.', 1, 13, 'vocabulary', ''],
  ['mi-unit-14', 'Ngā Tae (Colours & Describing)', 'Colours and the words that describe what you see.', 1, 14, 'vocabulary', ''],
  ['mi-unit-15', 'Ngā Kararehe (Animals)', 'Native birds, sea life, pets, farm animals — and the taonga species.', 1, 15, 'vocabulary', ''],
  ['mi-unit-16', 'Te Taiao (Nature & Weather)', 'Mountains, rivers, the sea — and the weather. Te taiao is the natural world that surrounds us.', 2, 16, 'vocabulary', ''],
  ['mi-unit-17', 'Ngā Kare-ā-Roto (Emotions)', 'The full range of feeling — koa (joy), pōuri (sadness), riri (anger), aroha (love).', 2, 17, 'vocabulary', ''],
  ['mi-unit-18', 'Te Whare (House & Home)', 'Rooms, household items, and the names for the parts of a wharenui.', 1, 18, 'vocabulary', ''],
  ['mi-unit-19', 'Te Pepeha (Introducing Yourself)', 'The Māori way of placing yourself — your mountain, your river, your people. The opening of every formal mihi.', 2, 19, 'vocabulary', ''],
  ['mi-unit-20', 'Whakataukī (Proverbs)', 'Whakataukī — wisdom packed into a phrase. The richest seam of te reo.', 3, 20, 'vocabulary', ''],
  ['mi-unit-21', 'Te Mahi (Work & Study)', 'School, work, and the language of mahi.', 2, 21, 'vocabulary', ''],
  ['mi-unit-22', 'Hauora (Health & Wellbeing)', 'The body, illness, and the Māori model of wellbeing (Te Whare Tapa Whā).', 2, 22, 'vocabulary', ''],
  ['mi-unit-23', 'Karakia me Waiata (Prayer & Song)', 'Karakia (incantations) and waiata (songs) — the spoken and sung heart of te reo.', 3, 23, 'vocabulary', ''],
  ['mi-unit-24', 'Te Ao Hou (Modern Life)', 'Phones, the internet, sports, and pop culture in te reo Māori.', 2, 24, 'vocabulary', ''],
  ['mi-unit-25', 'Ngā Whakaaro Matatau (Advanced Concepts)', 'Justice, freedom, sovereignty (rangatiratanga), and the words of the modern Māori conversation.', 3, 25, 'vocabulary', ''],
];

const REG = { N: 'neutral', F: 'formal', I: 'informal' };

module.exports.CARDS = [
  // ═══════════════ Unit 1 — First Words ═══════════════════════════════════════
  P('mi-unit-01', 'Kia ora',                   'hello / be well',                          'KEE-uh OH-rah',
    { tags: ['culture'],
      note: 'The everyday Māori greeting — also "thank you", "cheers", or simply acknowledgment. Literally "be well / be alive". Used across Aotearoa, even by non-speakers.' }),
  P('mi-unit-01', 'Tēnā koe',                  'hello (to one person, formal)',            'TAY-nah KOH-eh',
    { register: 'formal', tags: ['culture'],
      note: 'Formal greeting to ONE person. The plural forms agree with the listener — tēnā kōrua (two), tēnā koutou (three or more). Used in speeches and serious settings.' }),
  P('mi-unit-01', 'Tēnā kōrua',                'hello (to two people)',                    'TAY-nah KOH-roo-ah',
    { register: 'formal', tags: ['culture'] }),
  P('mi-unit-01', 'Tēnā koutou',               'hello (to three or more)',                 'TAY-nah KOH-toh',
    { register: 'formal', tags: ['culture'] }),
  P('mi-unit-01', 'Mōrena',                    'good morning',                             'MOH-reh-nah',
    { note: 'Transliteration of English "morning", but now thoroughly part of te reo.' }),
  P('mi-unit-01', 'Pō mārie',                  'good night',                               'POH MAH-ree-eh' ),
  P('mi-unit-01', 'Haere mai',                 'welcome (come here)',                      'HAI-reh MY',
    { tags: ['culture'],
      note: 'Literally "come hither" — used to welcome visitors, and the heart of the pōwhiri ceremony. The opposite, haere atu (go away from), parts company.' }),
  P('mi-unit-01', 'Haere rā',                  'goodbye (to one leaving)',                 'HAI-reh RAH',
    { note: 'Said to the person who is LEAVING. The stay/leave distinction matches Korean 안녕히 가세요 / 계세요.' }),
  P('mi-unit-01', 'E noho rā',                 'goodbye (to one staying)',                 'EH NOH-hoh RAH',
    { note: 'Said to the person who is STAYING — literally "remain there".' }),
  P('mi-unit-01', 'Hei konā',                  'see you later / bye',                      'HAY KOH-nah',
    { register: 'informal', note: 'Casual farewell — like "see ya". Hei konei rā is similar.' }),
  P('mi-unit-01', 'Kei te pēhea koe?',         'how are you?',                             'KAY teh PAY-heh-ah KOH-eh',
    { note: 'Singular. For two listeners: kei te pēhea kōrua? For three+: kei te pēhea koutou?' }),
  P('mi-unit-01', 'Kei te pai',                "I'm good / fine",                          'KAY teh PIE',
    { note: 'Literally "(it is) good". Pai is the catch-all word for "good / fine / okay".' }),
  P('mi-unit-01', 'Ka pai',                    'good / well done',                         'KAH PIE',
    { note: 'Praise — "good job", "nice one". Used constantly.' }),
  P('mi-unit-01', 'Kia ora rawa atu',          'thanks very much',                         'KEE-uh OH-rah RAH-wah AH-too' ),
  P('mi-unit-01', 'Aroha mai',                 "sorry / forgive me",                       'AH-roh-hah MY',
    { note: 'Literally "send love this way". A softer, more relational apology than English "sorry".' }),
  P('mi-unit-01', 'Tihei mauri ora!',          'behold, the breath of life!',              'TIH-hay MAU-ree OH-rah',
    { tags: ['culture'],
      note: 'A classical opening cry — used to begin a formal mihi or to claim the right to speak. Roots: tihei (sneeze), mauri (life force), ora (alive). A ritual claim that one is alive and has something to say.' }),
  V('mi-unit-01', 'āe',                        'yes',                                      'AH-eh',
    { pos: 'interjection' }),
  V('mi-unit-01', 'kāo',                       'no',                                       'KAH-oh',
    { pos: 'interjection', note: '"Kāore" is also "no / not"; in casual speech, the response is just kāo.' }),
  P('mi-unit-01', 'Ko wai tō ingoa?',          'what is your name?',                       'KOH WHY TOH ING-oh-ah' ),
  P('mi-unit-01', 'Ko ___ tōku ingoa',         'my name is ___',                           'KOH ___ TOH-koo ING-oh-ah' ),
  P('mi-unit-01', 'Nō hea koe?',               'where are you from?',                      'NOH HEH-ah KOH-eh' ),
  P('mi-unit-01', 'Nō ___ ahau',               'I am from ___',                            'NOH ___ ah-HOW' ),

  // ═══════════════ Unit 2 — Question Words & Pronouns ════════════════════════
  V('mi-unit-02', 'au',                        'I / me',                                   'OW',
    { pos: 'pronoun', note: 'Both "au" and "ahau" mean "I" — interchangeable, with "ahau" being slightly more formal.' }),
  V('mi-unit-02', 'ahau',                      'I / me (alt)',                             'ah-HOW',
    { pos: 'pronoun' }),
  V('mi-unit-02', 'koe',                       'you (one person)',                         'KOH-eh',
    { pos: 'pronoun', note: 'Singular "you". The plural forms (kōrua, koutou) tell the listener whether you mean two or three+.' }),
  V('mi-unit-02', 'ia',                        'he / she',                                 'EE-ah',
    { pos: 'pronoun', note: 'Te reo has no gendered pronouns — ia covers both he and she.' }),
  V('mi-unit-02', 'tāua',                      'we two (you and me)',                      'TAH-oo-ah',
    { pos: 'pronoun', tags: ['culture'],
      note: 'Te reo distinguishes inclusive vs exclusive "we", and dual vs plural. Tāua = you + me. Māua = me + someone else (not you). This precision matters in greetings and waiata.' }),
  V('mi-unit-02', 'māua',                      'we two (he/she and me, not you)',          'MAH-oo-ah',
    { pos: 'pronoun', tags: ['culture'] }),
  V('mi-unit-02', 'tātou',                     'we (you, me, and others)',                 'TAH-toh',
    { pos: 'pronoun', tags: ['culture'], note: 'Inclusive "we", 3+ people. Used in formal mihi: "tātou katoa" = all of us.' }),
  V('mi-unit-02', 'mātou',                     'we (others and me, not you)',              'MAH-toh',
    { pos: 'pronoun', tags: ['culture'] }),
  V('mi-unit-02', 'kōrua',                     'you two',                                  'KOH-roo-ah',
    { pos: 'pronoun' }),
  V('mi-unit-02', 'koutou',                    'you (three or more)',                      'KOH-toh',
    { pos: 'pronoun' }),
  V('mi-unit-02', 'rāua',                      'they two',                                 'RAH-oo-ah',
    { pos: 'pronoun' }),
  V('mi-unit-02', 'rātou',                     'they (three or more)',                     'RAH-toh',
    { pos: 'pronoun' }),
  V('mi-unit-02', 'wai',                       'who',                                      'WHY',
    { pos: 'pronoun', note: '"Ko wai?" = "who?". Always paired with ko in this construction.' }),
  V('mi-unit-02', 'aha',                       'what',                                     'AH-hah',
    { pos: 'pronoun', note: '"He aha?" = "what is it?". Wai asks about people; aha asks about things.' }),
  V('mi-unit-02', 'hea',                       'where',                                    'HEH-ah',
    { pos: 'pronoun', note: '"Kei hea?" = "where is it?". Combines with location particles (nō hea = from where, ki hea = to where).' }),
  V('mi-unit-02', 'āhea',                      'when (future)',                            'AH-heh-ah',
    { pos: 'pronoun', note: '"Āhea?" asks about FUTURE time. For past time, use "Nōnahea?".' }),
  V('mi-unit-02', 'nōnahea',                   'when (past)',                              'NOH-nah-heh-ah',
    { pos: 'pronoun' }),
  V('mi-unit-02', 'he aha ai',                 'why',                                      'HEH AH-hah eye',
    { pos: 'pronoun', note: 'Literally "for what reason".' }),
  V('mi-unit-02', 'pēhea',                     'how',                                      'PAY-heh-ah',
    { pos: 'pronoun', note: '"Kei te pēhea?" = "how is it?". The greeting "kei te pēhea koe?" uses this.' }),
  V('mi-unit-02', 'tēnei',                     'this (near me)',                           'TAY-nay',
    { pos: 'pronoun', note: 'Te reo has THREE demonstratives by distance: tēnei (near me), tēnā (near you), tērā (far from both). Plurals: ēnei, ēnā, ērā.' }),
  V('mi-unit-02', 'tēnā',                      'that (near you)',                          'TAY-nah',
    { pos: 'pronoun' }),
  V('mi-unit-02', 'tērā',                      'that (over there)',                        'TAY-rah',
    { pos: 'pronoun' }),
  V('mi-unit-02', 'tangata',                   'person',                                   'TAH-ngah-tah',
    { note: 'Plural: tāngata (with macron on the first ā) — the macron alone marks the plural. Same for tamaiti / tamariki (child / children), wahine / wāhine (woman / women).' }),
  V('mi-unit-02', 'tamaiti',                   'child',                                    'tah-MY-tee',
    { note: 'Plural: tamariki. Children sit at the heart of te ao Māori.' }),
  V('mi-unit-02', 'tāne',                      'man',                                      'TAH-neh' ),
  V('mi-unit-02', 'wahine',                    'woman',                                    'WAH-hee-neh',
    { note: 'Plural: wāhine — macron-only plural.' }),
  V('mi-unit-02', 'hoa',                       'friend',                                   'HOH-ah' ),

  // ═══════════════ Unit 3 — Numbers ══════════════════════════════════════════
  V('mi-unit-03', 'tahi',                      'one (1)',                                  'TAH-hee', { pos: 'number' }),
  V('mi-unit-03', 'rua',                       'two (2)',                                  'ROO-ah',  { pos: 'number' }),
  V('mi-unit-03', 'toru',                      'three (3)',                                'TOH-roo', { pos: 'number' }),
  V('mi-unit-03', 'whā',                       'four (4)',                                 'FAH',     { pos: 'number',
    note: 'WH in te reo is usually pronounced /f/ — whā ≈ "fah", whare ≈ "FAH-reh". Some northern dialects keep an older /ʍ/ or even /w/.' }),
  V('mi-unit-03', 'rima',                      'five (5)',                                 'REE-mah', { pos: 'number' }),
  V('mi-unit-03', 'ono',                       'six (6)',                                  'OH-noh',  { pos: 'number' }),
  V('mi-unit-03', 'whitu',                     'seven (7)',                                'FEE-too', { pos: 'number' }),
  V('mi-unit-03', 'waru',                      'eight (8)',                                'WAH-roo', { pos: 'number' }),
  V('mi-unit-03', 'iwa',                       'nine (9)',                                 'EE-wah',  { pos: 'number' }),
  V('mi-unit-03', 'tekau',                     'ten (10)',                                 'TEH-kow', { pos: 'number' }),
  V('mi-unit-03', 'tekau mā tahi',             'eleven (11)',                              'TEH-kow MAH TAH-hee', { pos: 'number',
    note: '11–19 are formed "tekau mā [unit]" — literally "ten and one".' }),
  V('mi-unit-03', 'rua tekau',                 'twenty (20)',                              'ROO-ah TEH-kow', { pos: 'number',
    note: 'Multiples of ten: number + tekau. 30 = toru tekau, 40 = whā tekau, etc.' }),
  V('mi-unit-03', 'rau',                       'hundred (100)',                            'ROW',     { pos: 'number',
    note: 'One hundred = kotahi rau. Also means "leaf" — different word, same spelling.' }),
  V('mi-unit-03', 'mano',                      'thousand (1000)',                          'MAH-noh', { pos: 'number' }),
  V('mi-unit-03', 'kore',                      'zero',                                     'KOH-reh', { pos: 'number',
    note: 'Also "none / not". "Kore rawa" = "absolutely not".' }),

  // ═══════════════ Unit 4 — Everyday Phrases ═════════════════════════════════
  P('mi-unit-04', 'E hia te utu?',             'how much does it cost?',                   'EH HEE-ah teh OO-too' ),
  P('mi-unit-04', 'Kei hea te wharepaku?',     'where is the toilet?',                     'KAY HEH-ah teh FAH-reh-PAH-koo',
    { note: 'Wharepaku = small house. Toilets are tapu (set apart) in te ao Māori — never to be located near where food is prepared.' }),
  P('mi-unit-04', 'Āwhinatia mai',             'help me',                                  'AH-fee-nah-tee-ah MY' ),
  P('mi-unit-04', 'Kāore au i te mōhio',       "I don't know",                             'KAH-oh-reh OW EE teh MOH-hee-oh' ),
  P('mi-unit-04', 'Kōrero mai i te āta',       'please speak slowly',                      'KOH-reh-roh MY ee teh AH-tah' ),
  P('mi-unit-04', 'E kōrero ana koe i te reo Pākehā?', 'do you speak English?',            'EH KOH-reh-roh AH-nah KOH-eh ee teh REH-oh PAH-keh-hah' ),
  P('mi-unit-04', 'He pai',                    "it's good / okay",                         'HEH PIE' ),
  P('mi-unit-04', 'Tēnā koa',                  'please',                                   'TAY-nah KOH-ah',
    { register: 'formal', note: 'Polite request marker — added before or after a request to soften it.' }),
  P('mi-unit-04', 'Mauruuru',                  'thank you',                                'MAH-oo-ROO-roo',
    { note: 'A warmer, more grateful "thank you" than kia ora. "Mauruuru koe" = thank you (sg). Often spelled ngā mihi for written thanks.' }),
  P('mi-unit-04', 'Ngā mihi',                  'thanks / greetings (written)',             'NGAH MEE-hee',
    { tags: ['culture'], note: 'The standard sign-off in emails and letters — like "regards". "Ngā mihi nui" intensifies it.' }),
  P('mi-unit-04', 'Heoi anō',                  "that's all / anyway",                      'HEH-oh-ee AH-noh',
    { note: 'Transition word — used to wrap up or pivot in a kōrero.' }),

  // ═══════════════ Unit 5 — Kai (Food & Drink) ═══════════════════════════════
  V('mi-unit-05', 'kai',                       'food / to eat',                            'KIGH',
    { tags: ['culture'], note: 'Kai is both noun and verb — food and the act of eating. "Kai!" called out means "food\'s ready, come eat".' }),
  V('mi-unit-05', 'wai',                       'water',                                    'WHY',
    { note: 'Also asks "who?" in some constructions — context disambiguates.' }),
  V('mi-unit-05', 'kāwhe',                     'coffee',                                   'KAH-feh' ),
  V('mi-unit-05', 'tī',                        'tea',                                      'TEE' ),
  V('mi-unit-05', 'pia',                       'beer',                                     'PEE-ah' ),
  V('mi-unit-05', 'parāoa',                    'bread',                                    'PAH-rah-OH-ah' ),
  V('mi-unit-05', 'huawhenua',                 'vegetables',                               'HOO-ah-FEH-noo-ah',
    { note: 'Literally "fruit of the land" — hua (fruit) + whenua (land).' }),
  V('mi-unit-05', 'hua rākau',                 'fruit',                                    'HOO-ah RAH-kow',
    { note: 'Literally "fruit of the tree".' }),
  V('mi-unit-05', 'mīti',                      'meat',                                     'MEE-tee' ),
  V('mi-unit-05', 'ika',                       'fish',                                     'EE-kah',
    { tags: ['culture'], note: 'Fishing was and is central to Māori life. Tangaroa is the atua (deity) of the sea — there are karakia (prayers) for taking fish.' }),
  V('mi-unit-05', 'kūmara',                    'sweet potato',                             'KOO-mah-rah',
    { tags: ['culture'], note: 'A staple of pre-contact Māori cuisine. The orange sweet potato is the modern variety; older varieties (taewa, hua kūmara) are still grown.' }),
  V('mi-unit-05', 'hāngī',                     'hāngī (earth-oven feast)',                 'HAH-ngee',
    { tags: ['culture'], note: 'Food cooked in an earth oven — wrapped baskets of meat and vegetables steamed over hot stones in a pit. Reserved for celebrations and hui.' }),
  V('mi-unit-05', 'kaimoana',                  'seafood',                                  'KIGH-moh-AH-nah',
    { tags: ['culture'], note: 'Literally "food of the sea" — pāua, kina, mussels, fish. Gathering kaimoana is a customary right protected by tikanga.' }),
  V('mi-unit-05', 'pāua',                      'pāua (abalone)',                           'PAH-oo-ah',
    { tags: ['culture'], note: 'The iridescent shell of the pāua is a taonga — used in carving and jewellery. The meat is a delicacy.' }),
  V('mi-unit-05', 'kina',                      'sea urchin',                               'KEE-nah', { tags: ['culture'] }),
  V('mi-unit-05', 'rēwena',                    'Māori sourdough bread',                    'RAY-weh-nah', { tags: ['culture'],
    note: 'Traditional Māori bread leavened with a potato starter (the "bug"). Passed down within whānau.' }),
  P('mi-unit-05', 'Kei te hiakai au',          "I'm hungry",                               'KAY teh HEE-ah-kigh OW' ),
  P('mi-unit-05', 'Kei te hiainu au',          "I'm thirsty",                              'KAY teh HEE-ah-ee-noo OW' ),
  P('mi-unit-05', 'He reka tēnei',             'this is delicious',                        'HEH REH-kah TAY-nay' ),

  // ═══════════════ Unit 6 — Common Verbs (dictionary forms) ══════════════════
  V('mi-unit-06', 'haere',                     'go / come / travel',                       'HAI-reh',
    { pos: 'verb', note: 'The all-purpose motion verb. Haere mai = come here; haere atu = go away from; haere rā = goodbye (to one leaving).' }),
  V('mi-unit-06', 'noho',                      'sit / stay / live',                        'NOH-hoh',
    { pos: 'verb', note: 'Also "to live (somewhere)". E noho rā = stay well (goodbye to one staying).' }),
  V('mi-unit-06', 'kai',                       'eat',                                      'KIGH',
    { pos: 'verb', note: 'Same word as the noun "food".' }),
  V('mi-unit-06', 'inu',                       'drink',                                    'EE-noo', { pos: 'verb' }),
  V('mi-unit-06', 'moe',                       'sleep',                                    'MOH-eh',
    { pos: 'verb', note: 'Also means "marry" — moe can refer to spending the night together in either sense; context distinguishes.' }),
  V('mi-unit-06', 'titiro',                    'look / watch',                             'TEE-tee-roh', { pos: 'verb' }),
  V('mi-unit-06', 'whakarongo',                'listen',                                   'FAH-kah-ROH-ngoh', { pos: 'verb',
    note: 'Whaka- is a causative prefix: whakarongo = "cause to be heard" = "listen". The prefix is everywhere — whakapapa, whakaaro, whakaiti.' }),
  V('mi-unit-06', 'kōrero',                    'speak / talk / story',                     'KOH-reh-roh',
    { pos: 'verb', note: 'Both verb (to speak) and noun (a story, a speech). The kōrero is central to Māori knowledge transmission.' }),
  V('mi-unit-06', 'pānui',                     'read / announce',                          'PAH-noo-ee',
    { pos: 'verb', note: 'Also "to announce" — a pānui is a public notice. The verb covers both reading aloud and the publication itself.' }),
  V('mi-unit-06', 'tuhi',                      'write / draw',                             'TOO-hee', { pos: 'verb' }),
  V('mi-unit-06', 'ako',                       'learn / teach',                            'AH-koh',
    { pos: 'verb', tags: ['culture'],
      note: 'Beautifully, ako means BOTH "learn" and "teach" — reflecting the Māori view that teacher and learner exchange roles. Ako is a core tenet of kura kaupapa (Māori-medium schools).' }),
  V('mi-unit-06', 'mahi',                      'do / work',                                'MAH-hee',
    { pos: 'verb', note: 'Also noun — "work", "task", "job". Mahi-ā-rēhia = leisure / recreational activity.' }),
  V('mi-unit-06', 'mōhio',                     'know',                                     'MOH-hee-oh', { pos: 'verb' }),
  V('mi-unit-06', 'hiahia',                    'want / desire',                            'HEE-ah-HEE-ah', { pos: 'verb' }),
  V('mi-unit-06', 'aroha',                     'love / compassion',                        'AH-roh-hah',
    { pos: 'verb', tags: ['culture'],
      note: 'Aroha is bigger than English "love" — it includes compassion, empathy, and the bond between people. Aroha ki te tangata = love for humanity is a guiding value.' }),
  V('mi-unit-06', 'kata',                      'laugh',                                    'KAH-tah', { pos: 'verb' }),
  V('mi-unit-06', 'tangi',                     'cry / mourn / sound',                      'TAH-ngee',
    { pos: 'verb', tags: ['culture'],
      note: 'Both "cry" and "the sound a thing makes". A tangihanga is a funeral — literally "the act of crying for".' }),
  V('mi-unit-06', 'waiata',                    'sing / song',                              'WHY-ah-tah',
    { pos: 'verb', tags: ['culture'],
      note: 'Waiata are sung at virtually every formal occasion — to support a speaker, to welcome, to mourn. Knowing a waiata is knowing a piece of identity.' }),
  V('mi-unit-06', 'oma',                       'run',                                      'OH-mah', { pos: 'verb' }),
  V('mi-unit-06', 'whakaaro',                  'think',                                    'FAH-kah-AH-roh',
    { pos: 'verb', note: 'Also "an idea, a thought". He whakaaro pai = a good idea.' }),
  V('mi-unit-06', 'tiki',                      'fetch / get',                              'TEE-kee',
    { pos: 'verb', note: 'A hei-tiki is a carved pendant (a "thing fetched / a treasure").' }),
  V('mi-unit-06', 'hoatu',                     'give (away from speaker)',                 'hoh-AH-too',
    { pos: 'verb', note: 'Te reo distinguishes giving direction: hoatu = give away; homai = give toward me.' }),
  V('mi-unit-06', 'homai',                     'give (toward speaker)',                    'HOH-my',
    { pos: 'verb' }),
  V('mi-unit-06', 'pai',                       'good / okay',                              'PIE',
    { pos: 'adjective', note: 'The catch-all "good". Stative — used directly without a tense particle: "He pai." = "(it is) good."' }),
  V('mi-unit-06', 'kino',                      'bad',                                      'KEE-noh',
    { pos: 'adjective', note: 'Also "very" as an intensifier: pai kino = "really good".' }),
  V('mi-unit-06', 'nui',                       'big / great',                              'NOO-ee',
    { pos: 'adjective', note: 'Also "important". Ngā mihi nui = with big/great thanks.' }),
  V('mi-unit-06', 'iti',                       'small',                                    'EE-tee', { pos: 'adjective' }),
  V('mi-unit-06', 'reka',                      'sweet / delicious',                        'REH-kah', { pos: 'adjective' }),
  V('mi-unit-06', 'māmā',                      'easy / light',                             'MAH-MAH', { pos: 'adjective' }),
  V('mi-unit-06', 'uaua',                      'hard / difficult',                         'OO-ah-OO-ah', { pos: 'adjective' }),

  // ═══════════════ Unit 7 — Grammar (tense particles + possession) ═══════════
  { unit: 'mi-unit-07', mi: 'kei te',          en: 'present continuous marker (am / is / are -ing)', pron: 'KAY teh', type: 'grammar', pos: 'particle',
    note: 'PRECEDES the verb. "Kei te kai au" = "I am eating". The negative is "Kāore au i te kai" — kāore replaces kei and the marker shifts to "i te".' },
  { unit: 'mi-unit-07', mi: 'kua',             en: 'perfective marker (have done)',                  pron: 'KOO-ah', type: 'grammar', pos: 'particle',
    note: '"Kua oti" = "(it) has been completed". Marks a completed change of state.' },
  { unit: 'mi-unit-07', mi: 'i',               en: 'past marker',                                     pron: 'EE', type: 'grammar', pos: 'particle',
    note: '"I haere au" = "I went". Also marks the direct object of an action — i has two roles, disambiguated by position.' },
  { unit: 'mi-unit-07', mi: 'ka',              en: 'inceptive / future / general marker',             pron: 'KAH', type: 'grammar', pos: 'particle',
    note: 'A flexible particle — marks an event starting (inceptive), a habitual action, or a future event. "Ka kite anō" = "see (you) again".' },
  { unit: 'mi-unit-07', mi: 'e ... ana',       en: 'continuous marker (frame around verb)',           pron: 'EH ... AH-nah', type: 'grammar', pos: 'particle',
    note: 'Wraps the verb: "E kai ana au" = "I am eating". Often interchangeable with "kei te" but flavoured slightly differently — closer to "is currently doing".' },
  { unit: 'mi-unit-07', mi: 'me',              en: 'should',                                          pron: 'MEH', type: 'grammar', pos: 'particle',
    note: '"Me haere tāua" = "we two should go". A polite, soft directive.' },
  { unit: 'mi-unit-07', mi: 'kia',             en: 'subjunctive / let it be',                         pron: 'KEE-ah', type: 'grammar', pos: 'particle',
    note: '"Kia ora" literally = "let (you) be well". A wish or call for a state to come about.' },
  { unit: 'mi-unit-07', mi: 'tā / tō',         en: 'possessive (your, formal)',                       pron: 'TAH / TOH', type: 'grammar', pos: 'particle',
    note: 'Possession in te reo splits into two categories: ā-form for things you have authority over (children, food, clothes you give), ō-form for things that are part of you or that you depend on (body parts, parents, transport you ride in, places). NOT a quirk — it encodes a worldview.' },
  { unit: 'mi-unit-07', mi: 'ngā',             en: 'the (plural)',                                    pron: 'NGAH', type: 'grammar', pos: 'particle',
    note: 'Te reo has TWO definite articles: te (singular) and ngā (plural). "Te whare" = the house; "ngā whare" = the houses. The noun itself often does not change.' },
  { unit: 'mi-unit-07', mi: 'te',              en: 'the (singular)',                                  pron: 'TEH', type: 'grammar', pos: 'particle' },
  { unit: 'mi-unit-07', mi: 'he',              en: 'a / some (indefinite)',                          pron: 'HEH', type: 'grammar', pos: 'particle',
    note: '"He whare" = "a house" or "some houses". The indefinite article doesn\'t distinguish singular and plural.' },
  { unit: 'mi-unit-07', mi: 'ki',              en: 'to / at',                                        pron: 'KEE', type: 'grammar', pos: 'particle',
    note: 'Direction or recipient: "Haere ki te kāinga" = "Go to the home".' },
  { unit: 'mi-unit-07', mi: 'i',               en: 'from / at (location of action)',                 pron: 'EE', type: 'grammar', pos: 'particle',
    note: 'Different "i" from the past-tense one. "I te whare" = "at / from the house".' },
  { unit: 'mi-unit-07', mi: 'nō',              en: 'from (origin / belonging)',                      pron: 'NOH', type: 'grammar', pos: 'particle',
    note: '"Nō hea koe?" = "where are you from?" — asks about origin / belonging, not location.' },
  { unit: 'mi-unit-07', mi: 'ko',              en: 'topic / identifying particle',                   pron: 'KOH', type: 'grammar', pos: 'particle',
    note: 'Equates two things or marks a topic. "Ko ___ tōku ingoa" = "___ is my name". "Ko" opens almost every line of a pepeha.' },

  // ═══════════════ Unit 8 — Whānau (Family) ══════════════════════════════════
  V('mi-unit-08', 'whānau',                    'family (extended)',                        'FAH-now',
    { tags: ['culture'],
      note: 'Whānau means EXTENDED family — parents, children, grandparents, cousins, in-laws, the whole network of relations. The English "nuclear family" is a much smaller idea.' }),
  V('mi-unit-08', 'hapū',                      'sub-tribe',                                'HAH-poo',
    { tags: ['culture'],
      note: 'A group of related whānau — the level of organisation at which most day-to-day decisions are traditionally made. Each hapū has its own marae.' }),
  V('mi-unit-08', 'iwi',                       'tribe / people',                           'EE-wee',
    { tags: ['culture'],
      note: 'A confederation of hapū tracing descent from a common ancestor. There are around 100 iwi across Aotearoa. Iwi also means "bones" — your iwi is your bones / your bloodline.' }),
  V('mi-unit-08', 'whakapapa',                 'genealogy / lineage',                      'FAH-kah-PAH-pah',
    { tags: ['culture'],
      note: 'Whakapapa is the layered web of who you descend from — connecting you to land, mountain, river, and people. Reciting your whakapapa is a way of claiming identity and place.' }),
  V('mi-unit-08', 'tūpuna',                    'ancestors',                                'TOO-poo-nah',
    { tags: ['culture'], note: 'Also spelled tīpuna. Reverence for ancestors threads through every formal occasion.' }),
  V('mi-unit-08', 'koroua',                    'old man / grandfather',                    'KOH-roh-OO-ah',
    { tags: ['culture'], note: 'Often shortened to "koro" — a respectful term for an elder man, not necessarily your biological grandfather.' }),
  V('mi-unit-08', 'kuia',                      'old woman / grandmother',                  'KOO-ee-ah',
    { tags: ['culture'], note: 'A respected elder woman. Kuia are central to ceremonial life — they lead the karanga at a pōwhiri.' }),
  V('mi-unit-08', 'matua',                     'father / parent',                          'MAH-too-ah',
    { note: 'Also broader "elder, parent". Pāpā is the affectionate form ("dad").' }),
  V('mi-unit-08', 'whaea',                     'mother / aunty',                           'FAH-eh-ah',
    { note: 'Also a respectful term for an older woman (similar to māmā being affectionate "mum").' }),
  V('mi-unit-08', 'pāpā',                      'dad',                                      'PAH-PAH' ),
  V('mi-unit-08', 'māmā',                      'mum',                                      'MAH-MAH' ),
  V('mi-unit-08', 'tama',                      'son',                                      'TAH-mah' ),
  V('mi-unit-08', 'tamāhine',                  'daughter',                                 'tah-MAH-hee-neh' ),
  V('mi-unit-08', 'tuakana',                   'older sibling (same gender)',              'TOO-ah-KAH-nah',
    { tags: ['culture'],
      note: 'A SAME-GENDER older sibling. The tuakana / teina relationship is core — older mentors younger. In modern usage, it also describes any senior-junior teaching pair.' }),
  V('mi-unit-08', 'teina',                     'younger sibling (same gender)',            'TEH-ee-nah',
    { tags: ['culture'] }),
  V('mi-unit-08', 'tungāne',                   "woman's brother",                          'too-NGAH-neh',
    { tags: ['culture'], note: 'The OPPOSITE-GENDER sibling words — like Korean 오빠 / 형. A woman calls her brother tungāne; a man calls his sister tuahine.' }),
  V('mi-unit-08', 'tuahine',                   "man's sister",                             'TOO-ah-HEE-neh', { tags: ['culture'] }),
  V('mi-unit-08', 'mokopuna',                  'grandchild',                               'MOH-koh-POO-nah',
    { note: 'Often shortened to "moko". Used affectionately for any child you have a close bond with.' }),
  V('mi-unit-08', 'kāinga',                    'home / village',                           'KAH-ee-ngah',
    { tags: ['culture'], note: 'Both "home" and "settlement / village" — the place where your whānau lives.' }),

  // ═══════════════ Unit 9 — Marae & Tikanga ══════════════════════════════════
  V('mi-unit-09', 'marae',                     'tribal meeting grounds',                   'MAH-rye',
    { tags: ['culture'],
      note: 'The marae is the gathering place of an iwi or hapū — a cluster of buildings around an open space (the marae ātea) where formal welcomes, funerals, and meetings happen. It is the beating heart of Māori cultural life.' }),
  V('mi-unit-09', 'wharenui',                  'meeting house',                            'FAH-reh-NOO-ee',
    { tags: ['culture'],
      note: 'The carved meeting house on a marae — often named after an ancestor whose body is symbolically represented by the building (head, arms, spine, ribs).' }),
  V('mi-unit-09', 'wharekai',                  'dining hall',                              'FAH-reh-KIGH',
    { tags: ['culture'],
      note: 'The kitchen / dining building of a marae. Wharekai and wharenui are kept apart because food and sleeping/ceremony are tapu separations.' }),
  V('mi-unit-09', 'pōwhiri',                   'formal welcome ceremony',                  'POH-fee-ree',
    { tags: ['culture'],
      note: 'The full ceremonial welcome onto a marae — karanga (call), whaikōrero (speeches), waiata, hongi. A boundary-crossing ritual that turns manuhiri (visitors) into tangata whenua (people of the land) for the visit.' }),
  V('mi-unit-09', 'karanga',                   "ceremonial call (women's)",                'KAH-rah-ngah',
    { tags: ['culture'],
      note: 'The high, sung call by senior women that opens a pōwhiri — calling visitors onto the marae. It is a tapu and powerful act, traditionally reserved for kuia.' }),
  V('mi-unit-09', 'whaikōrero',                'formal oratory',                           'FY-koh-reh-roh',
    { tags: ['culture'],
      note: 'The art of formal speech-making — done by men in most iwi, in a strict order (tangata whenua then manuhiri, or vice versa depending on kawa). Each whaikōrero is followed by a waiata.' }),
  V('mi-unit-09', 'hongi',                     'pressing of noses (greeting)',             'HOH-ngee',
    { tags: ['culture'],
      note: 'The traditional greeting — pressing noses (and sometimes foreheads) together, sharing breath (hā) — the breath of life given by Tāne to the first woman.' }),
  V('mi-unit-09', 'manuhiri',                  'visitors',                                 'MAH-noo-HEE-ree',
    { tags: ['culture'] }),
  V('mi-unit-09', 'tangata whenua',            'people of the land / hosts',               'TAH-ngah-tah FEH-noo-ah',
    { tags: ['culture'],
      note: 'The hosts at a marae — the iwi or hapū of the land. By extension, "tangata whenua" also means Māori as the indigenous people of Aotearoa.' }),
  V('mi-unit-09', 'koha',                      'gift / contribution',                      'KOH-hah',
    { tags: ['culture'],
      note: 'A gift, usually money, given to a marae to contribute to the costs of hosting. It is an acknowledgement of manaakitanga, not a fee.' }),
  V('mi-unit-09', 'haka',                      'haka (posture dance)',                     'HAH-kah',
    { tags: ['culture'],
      note: 'A vigorous chanted dance with stylised body movements — used to challenge, welcome, mourn, or celebrate. The "Ka Mate" haka by the All Blacks is the most internationally known, but haka are countless and tribally specific.' }),
  V('mi-unit-09', 'tikanga',                   'protocol / customary practice',            'TEE-kah-ngah',
    { tags: ['culture'],
      note: 'The "right way" of doing things — the customs and protocols that guide Māori life. Each iwi has its own tikanga.' }),
  V('mi-unit-09', 'kawa',                      'marae protocol',                           'KAH-wah',
    { tags: ['culture'],
      note: 'The specific protocols of a marae — varies by iwi (e.g. whether visitors or hosts speak first). Breaking kawa is a serious matter.' }),
  V('mi-unit-09', 'tangihanga',                'funeral / mourning',                       'TAH-ngee-HAH-ngah',
    { tags: ['culture'],
      note: 'The Māori funeral — usually three days, held at the marae, with the body present. A taonga of Māori culture preserved by law (employers must allow attendance).' }),
  V('mi-unit-09', 'hui',                       'gathering / meeting',                      'HOO-ee',
    { note: 'Any kind of formal meeting — political, cultural, social. "Hui" has entered NZ English as the standard word for a meeting on Māori terms.' }),

  // ═══════════════ Unit 10 — Time & Days ═════════════════════════════════════
  V('mi-unit-10', 'i tēnei rā',                'today',                                    'EE TAY-nay RAH', { pos: 'noun' }),
  V('mi-unit-10', 'āpōpō',                     'tomorrow',                                 'AH-poh-POH', { pos: 'noun' }),
  V('mi-unit-10', 'inanahi',                   'yesterday',                                'EE-nah-NAH-hee', { pos: 'noun' }),
  V('mi-unit-10', 'ināianei',                  'now',                                      'EE-nah-EE-ah-nay', { pos: 'adverb' }),
  V('mi-unit-10', 'ata',                       'morning',                                  'AH-tah', { pos: 'noun' }),
  V('mi-unit-10', 'awatea',                    'midday / daylight',                        'AH-wah-TEH-ah', { pos: 'noun' }),
  V('mi-unit-10', 'ahiahi',                    'afternoon',                                'AH-hee-AH-hee', { pos: 'noun' }),
  V('mi-unit-10', 'pō',                        'night',                                    'POH', { pos: 'noun' }),
  V('mi-unit-10', 'haora',                     'hour',                                     'HAH-oh-rah', { pos: 'noun' }),
  V('mi-unit-10', 'meneti',                    'minute',                                   'MEH-neh-tee', { pos: 'noun' }),
  V('mi-unit-10', 'rā',                        'day / sun',                                'RAH',
    { pos: 'noun', tags: ['culture'], note: 'Both "day" and "sun" — Tama-nui-te-rā is the personification of the sun, "great son of the day".' }),
  V('mi-unit-10', 'wiki',                      'week',                                     'WEE-kee', { pos: 'noun' }),
  V('mi-unit-10', 'marama',                    'month / moon',                             'MAH-rah-mah',
    { pos: 'noun', tags: ['culture'], note: 'Both "moon" and "month" — Māori traditionally followed a lunar calendar (maramataka).' }),
  V('mi-unit-10', 'tau',                       'year',                                     'TOH', { pos: 'noun' }),
  V('mi-unit-10', 'Rāhina',                    'Monday',                                   'RAH-hee-nah', { pos: 'noun' }),
  V('mi-unit-10', 'Rātū',                      'Tuesday',                                  'RAH-too', { pos: 'noun' }),
  V('mi-unit-10', 'Rāapa',                     'Wednesday',                                'RAH-ah-pah', { pos: 'noun' }),
  V('mi-unit-10', 'Rāpare',                    'Thursday',                                 'RAH-pah-reh', { pos: 'noun' }),
  V('mi-unit-10', 'Rāmere',                    'Friday',                                   'RAH-meh-reh', { pos: 'noun' }),
  V('mi-unit-10', 'Rāhoroi',                   'Saturday',                                 'RAH-hoh-roy', { pos: 'noun' }),
  V('mi-unit-10', 'Rātapu',                    'Sunday',                                   'RAH-tah-poo',
    { pos: 'noun', tags: ['culture'], note: 'Literally "tapu day" — Sunday is set aside.' }),

  // ═══════════════ Unit 11 — Places ══════════════════════════════════════════
  V('mi-unit-11', 'whare',                     'house',                                    'FAH-reh', { pos: 'noun' }),
  V('mi-unit-11', 'kāinga',                    'home',                                     'KAH-ee-ngah', { pos: 'noun' }),
  V('mi-unit-11', 'kura',                      'school',                                   'KOO-rah',
    { pos: 'noun', tags: ['culture'], note: 'Kura kaupapa Māori are Māori-medium schools — a flagship of the language revival.' }),
  V('mi-unit-11', 'wharekura',                 'secondary school (Māori-medium)',          'FAH-reh-KOO-rah', { pos: 'noun', tags: ['culture'] }),
  V('mi-unit-11', 'whare wānanga',             'university',                               'FAH-reh WAH-nah-ngah',
    { pos: 'noun', tags: ['culture'], note: 'Literally "house of advanced learning". Pre-contact, wānanga were traditional schools of esoteric knowledge.' }),
  V('mi-unit-11', 'tāone',                     'town / city',                              'TAH-oh-neh', { pos: 'noun', note: 'From English "town".' }),
  V('mi-unit-11', 'taiwhenua',                 'countryside',                              'TY-fenoh-ah', { pos: 'noun' }),
  V('mi-unit-11', 'toa',                       'shop',                                     'TOH-ah', { pos: 'noun' }),
  V('mi-unit-11', 'wharepukapuka',             'library',                                  'FAH-reh-POO-kah-POO-kah', { pos: 'noun', note: 'Literally "house of books".' }),
  V('mi-unit-11', 'whare karakia',             'church',                                   'FAH-reh KAH-rah-KEE-ah', { pos: 'noun', note: 'Literally "house of prayer".' }),
  V('mi-unit-11', 'wharepaku',                 'toilet',                                   'FAH-reh-PAH-koo', { pos: 'noun' }),
  V('mi-unit-11', 'pātaka',                    'storehouse / pantry',                      'PAH-tah-kah',
    { pos: 'noun', tags: ['culture'], note: 'Traditional raised storehouse for food. "Te Pātaka Kōrero" = library / repository of knowledge.' }),
  V('mi-unit-11', 'taone nui',                 'big city',                                 'TY-oh-neh NOO-ee', { pos: 'noun' }),
  V('mi-unit-11', 'Aotearoa',                  'New Zealand',                              'AH-oh-teh-AH-roh-ah',
    { pos: 'noun', tags: ['culture'],
      note: 'Literally "land of the long white cloud" — the name given by Kupe\'s wife Kuramārōtini when she first sighted these islands. The country\'s officially recognised name alongside New Zealand.' }),
  V('mi-unit-11', 'Aotearoa whānui',           'wider New Zealand',                        'AH-oh-teh-AH-roh-ah FAH-noo-ee', { pos: 'noun' }),
  V('mi-unit-11', 'Te Ika-a-Māui',             'North Island',                             'teh EE-kah-ah-MAH-oo-ee',
    { pos: 'noun', tags: ['culture'], note: 'Literally "the fish of Māui" — the demi-god Māui fished it up from the sea.' }),
  V('mi-unit-11', 'Te Waipounamu',             'South Island',                             'teh WHY-poh-NAH-moo',
    { pos: 'noun', tags: ['culture'], note: 'Literally "the waters of greenstone (pounamu)" — the source of NZ\'s prized jade.' }),

  // ═══════════════ Unit 12 — Te Ao Māori (Cultural Concepts) ═════════════════
  V('mi-unit-12', 'mana',                      'prestige / spiritual authority',           'MAH-nah',
    { tags: ['culture'],
      note: 'Mana is hard to translate — a combination of prestige, authority, power, status, and spiritual force. You inherit some from your tūpuna, earn some through your deeds, and can lose some through misconduct. The single most important concept in te ao Māori.' }),
  V('mi-unit-12', 'tapu',                      'sacred / restricted',                      'TAH-poo',
    { tags: ['culture'],
      note: 'Tapu marks things that are set apart — sacred, restricted, dangerous, or special. The head is tapu (don\'t touch); a graveyard is tapu; certain places and times are tapu. The opposite is noa.' }),
  V('mi-unit-12', 'noa',                       'common / unrestricted',                    'NOH-ah',
    { tags: ['culture'],
      note: 'Noa is the absence of tapu — ordinary, free, accessible. Food, washing, and everyday cooked meals are noa. Specific rituals (whakanoa) move things from tapu to noa.' }),
  V('mi-unit-12', 'mauri',                     'life force',                               'MAH-oo-ree',
    { tags: ['culture'],
      note: 'The vital essence in every living thing — and in rivers, mountains, taonga objects. To "diminish someone\'s mauri" is to harm them spiritually.' }),
  V('mi-unit-12', 'wairua',                    'spirit / soul',                            'WHY-roo-ah',
    { tags: ['culture'],
      note: 'The spirit or soul — what continues after death and connects you to your tūpuna. "Wairua" is now an everyday word in NZ English for the feeling of a place.' }),
  V('mi-unit-12', 'manaakitanga',              'hospitality / kindness / generosity',      'MAH-nah-AH-kee-TAH-ngah',
    { tags: ['culture'],
      note: 'The duty of caring for visitors — feeding them well, looking after them, raising their mana. A core Māori value; "manaaki manuhiri" is the host\'s job.' }),
  V('mi-unit-12', 'kaitiakitanga',             'guardianship (of land, sea, taonga)',      'KIGH-tee-AH-kee-TAH-ngah',
    { tags: ['culture'],
      note: 'The obligation to act as a guardian — of the environment, of taonga, of knowledge. A core principle of Māori environmentalism and now enshrined in NZ law.' }),
  V('mi-unit-12', 'whanaungatanga',            'kinship / relationship-building',          'FAH-now-NGAH-tah-NGAH',
    { tags: ['culture'],
      note: 'The work of building and maintaining relationships — through whakapapa, shared meals, joint kaupapa. Often the FIRST thing addressed at a hui before any business.' }),
  V('mi-unit-12', 'rangatiratanga',            'sovereignty / self-determination',         'RAH-ngah-TEE-rah-TAH-ngah',
    { tags: ['culture'],
      note: 'Chiefly authority, self-determination — the right to govern your own affairs. The word at the heart of Te Tiriti o Waitangi: Article 2 guaranteed Māori "tino rangatiratanga" over their lands and taonga. A live political concept today.' }),
  V('mi-unit-12', 'kotahitanga',               'unity / oneness',                          'KOH-tah-hee-TAH-ngah',
    { tags: ['culture'] }),
  V('mi-unit-12', 'taonga',                    'treasure (object or intangible)',          'TAH-oh-ngah',
    { tags: ['culture'],
      note: 'A treasure — could be a carved heirloom, the land, a song, a language. Te reo Māori is itself a taonga. Te Tiriti pledges Crown protection of "taonga katoa" (all treasures).' }),
  V('mi-unit-12', 'whenua',                    'land / placenta',                          'FEH-noo-ah',
    { tags: ['culture'],
      note: 'Whenua means both LAND and PLACENTA — the placenta is traditionally buried in the land, tying a person to a place from birth. "Tangata whenua" = people of the land.' }),
  V('mi-unit-12', 'atua',                      'god / ancestor with power',                'AH-too-ah',
    { tags: ['culture'],
      note: 'The atua (Ranginui the sky, Papatūānuku the earth, Tāne god of forests, Tangaroa of the sea, Tūmatauenga of war) are personifications of natural forces — deeply present in karakia and the everyday.' }),
  V('mi-unit-12', 'Ranginui',                  'Sky Father',                               'RAH-ngee-NOO-ee',
    { tags: ['culture'], note: 'The atua of the sky — separated from his beloved Papatūānuku (Earth Mother) by their children to let light into the world. The foundational creation kōrero.' }),
  V('mi-unit-12', 'Papatūānuku',               'Earth Mother',                             'PAH-pah-TOO-ah-NOO-koo',
    { tags: ['culture'], note: 'The Earth Mother — every Māori has a relationship to her as the source of food and the resting place of the dead.' }),

  // ═══════════════ Unit 13 — Body Parts ══════════════════════════════════════
  V('mi-unit-13', 'māhunga',                   'head',                                     'MAH-hoo-ngah',
    { tags: ['culture'], note: 'The head is the most TAPU part of the body — don\'t touch someone\'s head casually, don\'t pass food over it.' }),
  V('mi-unit-13', 'mata',                      'face / eye',                               'MAH-tah', { note: 'Also "eye" — context distinguishes.' }),
  V('mi-unit-13', 'karu',                      'eye',                                      'KAH-roo' ),
  V('mi-unit-13', 'taringa',                   'ear',                                      'TAH-ree-ngah' ),
  V('mi-unit-13', 'ihu',                       'nose',                                     'EE-hoo', { tags: ['culture'], note: 'The nose meets in the hongi — pressing noses is sharing breath.' }),
  V('mi-unit-13', 'māngai',                    'mouth',                                    'MAH-ngigh' ),
  V('mi-unit-13', 'niho',                      'tooth',                                    'NEE-hoh' ),
  V('mi-unit-13', 'arero',                     'tongue',                                   'AH-reh-roh',
    { tags: ['culture'], note: 'The pūkana (wide-eyed, tongue-out face) of the haka shows fierce mana.' }),
  V('mi-unit-13', 'kakī',                      'neck',                                     'KAH-kee' ),
  V('mi-unit-13', 'pakihiwi',                  'shoulder',                                 'PAH-kee-HEE-wee' ),
  V('mi-unit-13', 'ringa',                     'arm / hand',                               'REE-ngah', { note: 'Covers both arm and hand. "Ringa ringa" = the hands (reduplicated for plural emphasis).' }),
  V('mi-unit-13', 'matikara',                  'finger',                                   'MAH-tee-KAH-rah' ),
  V('mi-unit-13', 'manawa',                    'heart',                                    'MAH-nah-wah', { note: 'Also "breath, courage". "Kia kaha te manawa" = strength of heart.' }),
  V('mi-unit-13', 'puku',                      'stomach / belly',                          'POO-koo', { note: '"Kei te puku" = "in the belly". Also colloquial for being pregnant.' }),
  V('mi-unit-13', 'tuarā',                     'back',                                     'TOO-ah-RAH' ),
  V('mi-unit-13', 'waewae',                    'leg / foot',                               'WHY-why' ),

  // ═══════════════ Unit 14 — Colours & Describing ════════════════════════════
  V('mi-unit-14', 'whero',                     'red',                                      'FEH-roh', { pos: 'adjective' }),
  V('mi-unit-14', 'kākāriki',                  'green',                                    'KAH-KAH-ree-kee',
    { pos: 'adjective', tags: ['culture'], note: 'Also the name of native parakeets — green parrots.' }),
  V('mi-unit-14', 'kikorangi',                 'blue (sky)',                               'KEE-koh-RAH-ngee', { pos: 'adjective' }),
  V('mi-unit-14', 'kōwhai',                    'yellow',                                   'KOH-fai',
    { pos: 'adjective', tags: ['culture'], note: 'Named after the kōwhai tree, with its golden flowers — a herald of spring.' }),
  V('mi-unit-14', 'mā',                        'white',                                    'MAH', { pos: 'adjective' }),
  V('mi-unit-14', 'pango',                     'black',                                    'PAH-ngoh', { pos: 'adjective' }),
  V('mi-unit-14', 'mangu',                     'black (alt)',                              'MAH-ngoo', { pos: 'adjective' }),
  V('mi-unit-14', 'parauri',                   'brown',                                    'PAH-rah-OO-ree', { pos: 'adjective' }),
  V('mi-unit-14', 'kahurangi',                 'sky blue / treasured',                     'KAH-hoo-RAH-ngee',
    { pos: 'adjective', tags: ['culture'], note: 'Also a metaphor for "treasured / precious".' }),
  V('mi-unit-14', 'roa',                       'long / tall',                              'ROH-ah', { pos: 'adjective' }),
  V('mi-unit-14', 'poto',                      'short',                                    'POH-toh', { pos: 'adjective' }),
  V('mi-unit-14', 'hou',                       'new',                                      'HOH', { pos: 'adjective' }),
  V('mi-unit-14', 'tawhito',                   'old (ancient)',                            'TAH-fee-toh', { pos: 'adjective' }),
  V('mi-unit-14', 'ātaahua',                   'beautiful',                                'AH-tah-AH-hoo-ah', { pos: 'adjective' }),
  V('mi-unit-14', 'wera',                      'hot',                                      'WEH-rah', { pos: 'adjective' }),
  V('mi-unit-14', 'mātao',                     'cold',                                     'MAH-tah-oh', { pos: 'adjective' }),

  // ═══════════════ Unit 15 — Animals ═════════════════════════════════════════
  V('mi-unit-15', 'manu',                      'bird',                                     'MAH-noo',
    { tags: ['culture'], note: 'Birds carry deep significance — they are the children of Tāne, and many are tapu or have specific kaitiaki status.' }),
  V('mi-unit-15', 'kiwi',                      'kiwi (native bird)',                       'KEE-wee',
    { tags: ['culture'], note: 'New Zealand\'s national symbol — a flightless nocturnal bird, deeply tied to Māori identity. "Kiwi" is now also the demonym for New Zealanders.' }),
  V('mi-unit-15', 'tūī',                       'tūī (native bird)',                        'TOO-EE',
    { tags: ['culture'], note: 'A native honeyeater with a distinctive white throat tuft. Famous for its complex song.' }),
  V('mi-unit-15', 'kererū',                    'wood pigeon',                              'KEH-reh-ROO',
    { tags: ['culture'], note: 'The large native pigeon — formerly hunted, now strictly protected as a taonga species.' }),
  V('mi-unit-15', 'pīwakawaka',                'fantail',                                  'PEE-wah-kah-WAH-kah',
    { tags: ['culture'], note: 'A tiny, fearless native bird that flits around you in the bush. In some tradition, an omen of death.' }),
  V('mi-unit-15', 'kākā',                      'native parrot',                            'KAH-KAH', { tags: ['culture'] }),
  V('mi-unit-15', 'kākāpō',                    'flightless parrot (critically endangered)','KAH-KAH-POH', { tags: ['culture'] }),
  V('mi-unit-15', 'kurī',                      'dog',                                      'KOO-ree',
    { tags: ['culture'], note: 'Pre-contact, "kurī" referred to the now-extinct Māori dog — a taonga companion. Now used generally for "dog".' }),
  V('mi-unit-15', 'ngeru',                     'cat',                                      'NGEH-roo',
    { note: 'Also "poti" — both are used.' }),
  V('mi-unit-15', 'hoiho',                     'horse',                                    'HOY-hoh', { note: 'Also the name of the yellow-eyed penguin (a different hoiho).' }),
  V('mi-unit-15', 'kau',                       'cow',                                      'KOW' ),
  V('mi-unit-15', 'hipi',                      'sheep',                                    'HEE-pee' ),
  V('mi-unit-15', 'ika',                       'fish',                                     'EE-kah' ),
  V('mi-unit-15', 'whai',                      'stingray',                                 'FYE',
    { tags: ['culture'], note: 'Also "to chase / pursue / follow" — a common verb.' }),
  V('mi-unit-15', 'tohorā',                    'whale',                                    'TOH-hoh-RAH',
    { tags: ['culture'], note: 'Whales are revered as guides and ancestors — Paikea the whale-rider is a famous tradition.' }),

  // ═══════════════ Unit 16 — Te Taiao (Nature & Weather) ═════════════════════
  V('mi-unit-16', 'maunga',                    'mountain',                                 'MAH-oo-ngah',
    { tags: ['culture'], note: 'Every iwi has a mountain that is central to its identity — named in pepeha. To name your maunga is to name yourself.' }),
  V('mi-unit-16', 'awa',                       'river',                                    'AH-wah',
    { tags: ['culture'], note: 'Rivers are ancestors — the Whanganui River is legally a person under NZ law since 2017.' }),
  V('mi-unit-16', 'moana',                     'sea / ocean / large lake',                 'MOH-ah-nah',
    { tags: ['culture'], note: 'Tangaroa is the atua of the moana.' }),
  V('mi-unit-16', 'roto',                      'lake',                                     'ROH-toh' ),
  V('mi-unit-16', 'ngahere',                   'forest',                                   'NGAH-heh-reh', { tags: ['culture'], note: 'Tāne is the atua of the forest.' }),
  V('mi-unit-16', 'rākau',                     'tree',                                     'RAH-kow' ),
  V('mi-unit-16', 'tai',                       'tide / coast',                             'TIE' ),
  V('mi-unit-16', 'one',                       'beach / sand',                             'OH-neh' ),
  V('mi-unit-16', 'rangi',                     'sky / day',                                'RAH-ngee', { tags: ['culture'], note: 'Ranginui is the personified sky father.' }),
  V('mi-unit-16', 'ua',                        'rain',                                     'OO-ah' ),
  V('mi-unit-16', 'hau',                       'wind',                                     'HOW' ),
  V('mi-unit-16', 'hukapapa',                  'snow / frost',                             'HOO-kah-PAH-pah' ),
  V('mi-unit-16', 'kapua',                     'cloud',                                    'KAH-poo-ah' ),
  V('mi-unit-16', 'whetū',                     'star',                                     'FEH-too', { tags: ['culture'], note: 'Stars are navigators — Matariki (the Pleiades) marks the Māori new year.' }),
  V('mi-unit-16', 'Matariki',                  'Matariki / Pleiades',                      'MAH-tah-REE-kee',
    { tags: ['culture'],
      note: 'The Pleiades star cluster — its midwinter rising marks the Māori new year. Since 2022, Matariki is a national public holiday in NZ.' }),

  // ═══════════════ Unit 17 — Emotions ════════════════════════════════════════
  V('mi-unit-17', 'koa',                       'happy / joyful',                           'KOH-ah', { pos: 'adjective' }),
  V('mi-unit-17', 'pōuri',                     'sad',                                      'POH-oo-ree', { pos: 'adjective' }),
  V('mi-unit-17', 'riri',                      'angry',                                    'REE-ree', { pos: 'adjective' }),
  V('mi-unit-17', 'mataku',                    'afraid',                                   'MAH-tah-koo', { pos: 'adjective' }),
  V('mi-unit-17', 'whakamā',                   'embarrassed / shy',                        'FAH-kah-MAH',
    { pos: 'adjective', tags: ['culture'],
      note: 'A culturally weighty emotion — a deep shame or shyness that can hold someone back from speaking up. Important to recognise and ease in others.' }),
  V('mi-unit-17', 'aroha',                     'love',                                     'AH-roh-hah', { pos: 'noun', tags: ['culture'] }),
  V('mi-unit-17', 'manawanui',                 'steadfast / brave',                        'MAH-nah-WAH-noo-ee',
    { pos: 'adjective', tags: ['culture'], note: 'Literally "big heart" — perseverance and resolve.' }),
  V('mi-unit-17', 'māharahara',                'worried',                                  'MAH-hah-rah-HAH-rah', { pos: 'adjective' }),
  V('mi-unit-17', 'hōhā',                      'annoyed / fed up',                         'HOH-HAH', { pos: 'adjective', note: 'A common everyday word — "I\'m over it".' }),
  V('mi-unit-17', 'pārekareka',                'fun / entertaining',                       'PAH-reh-kah-REH-kah', { pos: 'adjective' }),
  V('mi-unit-17', 'mauri tau',                 'calm / settled spirit',                    'MAH-oo-ree TOH',
    { pos: 'phrase', tags: ['culture'], note: 'Literally "settled life-force". A state of peace — the goal of many karakia and tikanga.' }),
  V('mi-unit-17', 'kaha',                      'strong',                                   'KAH-hah',
    { pos: 'adjective', tags: ['culture'], note: 'Kia kaha = "be strong" — a constant exhortation in te reo. Says everything in two words.' }),

  // ═══════════════ Unit 18 — House & Home ════════════════════════════════════
  V('mi-unit-18', 'rūma',                      'room',                                     'ROO-mah' ),
  V('mi-unit-18', 'rūma moe',                  'bedroom',                                  'ROO-mah MOH-eh', { note: 'Literally "sleeping room".' }),
  V('mi-unit-18', 'kīhini',                    'kitchen',                                  'KEE-hee-nee', { note: 'From English "kitchen".' }),
  V('mi-unit-18', 'rūma horoi',                'bathroom',                                 'ROO-mah HOH-roy', { note: 'Literally "washing room".' }),
  V('mi-unit-18', 'moenga',                    'bed',                                      'MOH-eh-ngah' ),
  V('mi-unit-18', 'tūru',                      'chair',                                    'TOO-roo' ),
  V('mi-unit-18', 'tēpu',                      'table',                                    'TAY-poo' ),
  V('mi-unit-18', 'matapihi',                  'window',                                   'MAH-tah-PEE-hee' ),
  V('mi-unit-18', 'tatau',                     'door',                                     'TAH-toh' ),
  V('mi-unit-18', 'pereti',                    'plate',                                    'PEH-reh-tee' ),
  V('mi-unit-18', 'kapu',                      'cup',                                      'KAH-poo' ),
  V('mi-unit-18', 'paoro',                     'lamp / light',                             'PAH-oh-roh' ),

  // ═══════════════ Unit 19 — Pepeha ══════════════════════════════════════════
  V('mi-unit-19', 'pepeha',                    'formal self-introduction',                 'PEH-peh-hah',
    { tags: ['culture'],
      note: 'A pepeha places you in the world — your maunga (mountain), awa (river), waka (canoe of your ancestors), iwi (tribe), hapū (sub-tribe), marae, and your name. Said when introducing yourself formally, especially on a marae.' }),
  V('mi-unit-19', 'waka',                      'canoe / ancestral vessel',                 'WAH-kah',
    { tags: ['culture'],
      note: 'In pepeha, your waka is the canoe your ancestors arrived on from Hawaiki — Tainui, Te Arawa, Mātaatua, Tākitimu, etc. Now also means any vehicle.' }),
  P('mi-unit-19', 'Ko ___ tōku maunga',        'My mountain is ___',                       'KOH ___ TOH-koo MAH-oo-ngah',
    { tags: ['culture'], note: 'The first line of a pepeha — name your mountain.' }),
  P('mi-unit-19', 'Ko ___ tōku awa',           'My river is ___',                          'KOH ___ TOH-koo AH-wah',
    { tags: ['culture'] }),
  P('mi-unit-19', 'Ko ___ tōku waka',          'My ancestral canoe is ___',                'KOH ___ TOH-koo WAH-kah',
    { tags: ['culture'] }),
  P('mi-unit-19', 'Ko ___ tōku iwi',           'My tribe is ___',                          'KOH ___ TOH-koo EE-wee',
    { tags: ['culture'] }),
  P('mi-unit-19', 'Ko ___ tōku hapū',          'My sub-tribe is ___',                      'KOH ___ TOH-koo HAH-poo',
    { tags: ['culture'] }),
  P('mi-unit-19', 'Ko ___ tōku marae',         'My marae is ___',                          'KOH ___ TOH-koo MAH-rye',
    { tags: ['culture'] }),
  P('mi-unit-19', 'Nō ___ ahau',               'I am from ___',                            'NOH ___ ah-HOW',
    { tags: ['culture'] }),
  P('mi-unit-19', 'Ko ___ tōku ingoa',         'My name is ___',                           'KOH ___ TOH-koo ING-oh-ah',
    { tags: ['culture'], note: 'The closing line of a pepeha — you give your name LAST, after placing yourself.' }),
  P('mi-unit-19', 'Nō reira, tēnā koutou katoa', 'And so, greetings to you all',           'NOH RAY-rah, TAY-nah KOH-toh KAH-toh-ah',
    { tags: ['culture'], note: 'The traditional sign-off to a pepeha or mihi — "and so, greetings to all of you".' }),

  // ═══════════════ Unit 20 — Whakataukī (Proverbs) ═══════════════════════════
  P('mi-unit-20', 'He aha te mea nui o te ao? He tangata, he tangata, he tangata.',
    'What is the most important thing in the world? People, people, people.',
    'HEH AH-hah teh MEH-ah NOO-ee oh teh OW',
    { tags: ['culture'], note: 'The most famous whakataukī. Quoted in countless speeches — a reminder that at the heart of everything are the people.' }),
  P('mi-unit-20', 'Whāia te iti kahurangi',    'Pursue that which is precious',            'FY-ah teh EE-tee KAH-hoo-RAH-ngee',
    { tags: ['culture'], note: 'Full form: "Whāia te iti kahurangi, ki te tūohu koe, me he maunga teitei" — "If you must bow, let it be to a lofty mountain." Aim high.' }),
  P('mi-unit-20', 'Ka mate, ka mate, ka ora, ka ora!', 'I die, I die, I live, I live!',   'KAH MAH-teh, KAH MAH-teh, KAH OH-rah, KAH OH-rah',
    { tags: ['culture'], note: 'The opening of "Ka Mate" — the most famous haka, composed by Te Rauparaha. About escape from death.' }),
  P('mi-unit-20', 'Mā mua ka kite a muri, mā muri ka ora a mua',
    'Those who lead give sight to those who follow; those who follow give life to those who lead',
    'MAH MOO-ah KAH KEE-teh AH MOO-ree, MAH MOO-ree KAH OH-rah AH MOO-ah',
    { tags: ['culture'], note: 'On the reciprocity of leadership. Leaders and followers depend on each other.' }),
  P('mi-unit-20', 'He moana pukepuke e ekengia e te waka',
    'A choppy sea can be navigated',                                                       'HEH MOH-ah-nah POO-keh-POO-keh eh EH-keh-NGEE-ah eh teh WAH-kah',
    { tags: ['culture'], note: 'On perseverance — difficult times can be sailed through.' }),
  P('mi-unit-20', 'Kia kaha, kia māia, kia manawanui',
    'Be strong, be brave, be steadfast',                                                  'KEE-ah KAH-hah, KEE-ah MY-ah, KEE-ah MAH-nah-WAH-noo-ee',
    { tags: ['culture'], note: 'A common closing exhortation in speeches and letters.' }),
  P('mi-unit-20', 'Iti rearea, teitei kahikatea, ka taea',
    'The small bellbird can reach the top of the giant kahikatea tree',                   'EE-tee REH-ah-REH-ah, TAY-tay KAH-hee-KAH-teh-ah, KAH TAH-eh-ah',
    { tags: ['culture'], note: 'Small does not mean incapable.' }),
  P('mi-unit-20', 'Ehara taku toa i te toa takitahi, engari he toa takitini',
    'My strength is not that of an individual, but that of the collective',               'EH-hah-rah TAH-koo TOH-ah ee teh TOH-ah TAH-kee-TAH-hee, EH-ngah-ree HEH TOH-ah TAH-kee-TEE-nee',
    { tags: ['culture'], note: 'A core Māori value — collective strength over individual achievement.' }),
  P('mi-unit-20', 'Nāku te rourou, nāu te rourou, ka ora ai te iwi',
    'With your food basket and my food basket, the people will thrive',                   'NAH-koo teh ROH-roh, NAH-oo teh ROH-roh, KAH OH-rah eye teh EE-wee',
    { tags: ['culture'], note: 'On cooperation — what we share together feeds the community. Quoted in modern policy contexts about collaboration.' }),
  P('mi-unit-20', 'He waka eke noa',           "we're all in this together (a canoe we all ride)", 'HEH WAH-kah EH-keh NOH-ah',
    { tags: ['culture'], note: 'Now a common motto for shared endeavour — even adopted by NZ government during crises.' }),

  // ═══════════════ Unit 21 — Mahi (Work & Study) ═════════════════════════════
  V('mi-unit-21', 'mahi',                      'work / job',                               'MAH-hee', { pos: 'noun' }),
  V('mi-unit-21', 'kaimahi',                   'worker',                                   'KIGH-mah-hee', { pos: 'noun' }),
  V('mi-unit-21', 'pirihimana',                'police officer',                           'PEE-ree-HEE-mah-nah', { pos: 'noun' }),
  V('mi-unit-21', 'kaiako',                    'teacher',                                  'KIGH-AH-koh', { pos: 'noun', note: 'Literally "person who teaches/learns" (kai-ako).' }),
  V('mi-unit-21', 'ākonga',                    'student',                                  'AH-koh-ngah', { pos: 'noun', note: 'Literally "one who is learning".' }),
  V('mi-unit-21', 'tākuta',                    'doctor',                                   'TAH-koo-tah', { pos: 'noun' }),
  V('mi-unit-21', 'tapuhi',                    'nurse',                                    'TAH-poo-hee', { pos: 'noun' }),
  V('mi-unit-21', 'kaitaka',                   'lawyer',                                   'KIGH-tah-kah', { pos: 'noun' }),
  V('mi-unit-21', 'pūkenga',                   'expert / lecturer',                        'POO-keh-ngah', { pos: 'noun' }),
  V('mi-unit-21', 'utu',                       'pay / cost / reciprocity',                 'OO-too',
    { pos: 'noun', tags: ['culture'], note: 'Utu is bigger than "payment" — it is the principle of reciprocity, balance. Historically also "revenge". Today, the wages or price you pay.' }),
  V('mi-unit-21', 'pukapuka',                  'book',                                     'POO-kah-POO-kah', { pos: 'noun' }),
  V('mi-unit-21', 'kī wāhi',                   'university subject',                       'KEE FAH-hee', { pos: 'noun' }),

  // ═══════════════ Unit 22 — Hauora ══════════════════════════════════════════
  V('mi-unit-22', 'hauora',                    'health / wellbeing',                       'HAH-oh-OH-rah',
    { tags: ['culture'],
      note: 'Hauora is a holistic concept — the Te Whare Tapa Whā model (Sir Mason Durie) describes wellbeing as four walls of a house: taha tinana (physical), taha hinengaro (mental), taha wairua (spiritual), taha whānau (family/social). All four must stand.' }),
  V('mi-unit-22', 'taha tinana',               'physical wellbeing',                       'TAH-hah TEE-nah-nah', { tags: ['culture'] }),
  V('mi-unit-22', 'taha hinengaro',            'mental wellbeing',                         'TAH-hah HEE-neh-NGAH-roh', { tags: ['culture'] }),
  V('mi-unit-22', 'taha wairua',               'spiritual wellbeing',                      'TAH-hah WHY-roo-ah', { tags: ['culture'] }),
  V('mi-unit-22', 'taha whānau',               'family / social wellbeing',                'TAH-hah FAH-now', { tags: ['culture'] }),
  V('mi-unit-22', 'māuiui',                    'sick / tired',                             'MAH-oo-ee-OO-ee', { pos: 'adjective' }),
  V('mi-unit-22', 'mate',                      'illness / death',                          'MAH-teh',
    { tags: ['culture'], note: 'Both "sick" and "dead" — context distinguishes. He mate = sickness; ka mate = die.' }),
  V('mi-unit-22', 'rongoā',                    'traditional medicine',                     'ROH-ngoh-AH',
    { tags: ['culture'],
      note: 'Traditional Māori medicine — using native plants, mirimiri (massage), karakia. A revival has restored rongoā as part of integrated health care.' }),
  V('mi-unit-22', 'mirimiri',                  'massage / healing touch',                  'MEE-ree-MEE-ree', { tags: ['culture'] }),
  V('mi-unit-22', 'whare hauora',              'health clinic',                            'FAH-reh HAH-oh-OH-rah' ),

  // ═══════════════ Unit 23 — Karakia & Waiata ════════════════════════════════
  V('mi-unit-23', 'karakia',                   'prayer / incantation',                     'KAH-rah-KEE-ah',
    { tags: ['culture'],
      note: 'Karakia are recited at almost every formal event — opening meetings, before meals, before significant work. Some are Christian; many are traditional. They settle the wairua and call on the atua.' }),
  V('mi-unit-23', 'waiata',                    'song',                                     'WHY-ah-tah',
    { tags: ['culture'],
      note: 'A waiata follows almost every formal whaikōrero (speech) to support the speaker. Everyone joins in — learning waiata is learning belonging.' }),
  V('mi-unit-23', 'waiata-ā-ringa',            'action song',                              'WHY-ah-tah-AH-REE-ngah',
    { tags: ['culture'], note: 'Sung with synchronised arm movements — performed at kapa haka competitions and on the marae.' }),
  V('mi-unit-23', 'mōteatea',                  'traditional chant',                        'MOH-teh-AH-teh-ah',
    { tags: ['culture'], note: 'Ancient sung poetry — laments, love songs, songs about events. The most prestigious form of waiata.' }),
  V('mi-unit-23', 'pao',                       'short topical song',                       'PAH-oh', { tags: ['culture'] }),
  V('mi-unit-23', 'kapa haka',                 'performing arts group',                    'KAH-pah HAH-kah',
    { tags: ['culture'],
      note: 'A group that performs Māori action songs, haka, and waiata. Kapa haka competitions (Te Matatini) are major cultural events.' }),
  V('mi-unit-23', 'mihi',                      'speech of greeting',                       'MEE-hee',
    { tags: ['culture'], note: 'A shorter greeting speech — what you do at the start of an email or meeting. "Ngā mihi" closes correspondence.' }),

  // ═══════════════ Unit 24 — Modern Life ═════════════════════════════════════
  V('mi-unit-24', 'waea',                      'phone',                                    'WAH-eh-ah', { note: 'From English "wire".' }),
  V('mi-unit-24', 'waea pūkoro',               'mobile phone',                             'WAH-eh-ah POO-koh-roh', { note: 'Literally "pocket phone".' }),
  V('mi-unit-24', 'rorohiko',                  'computer',                                 'ROH-roh-HEE-koh', { note: 'Literally "electric brain".' }),
  V('mi-unit-24', 'īpurangi',                  'internet',                                 'EE-poo-RAH-ngee', { note: 'Coined word — "i-pūrangi" loosely "network".' }),
  V('mi-unit-24', 'pae pāpori',                'social media',                             'PIE PAH-poh-ree' ),
  V('mi-unit-24', 'mata-ā-tuhi',               'website / digital screen',                 'MAH-tah-AH-TOO-hee' ),
  V('mi-unit-24', 'pouaka whakaata',           'television',                               'POH-ah-kah FAH-kah-AH-tah', { note: 'Literally "box for reflecting".' }),
  V('mi-unit-24', 'reo irirangi',              'radio',                                    'REH-oh EE-ree-RAH-ngee' ),
  V('mi-unit-24', 'whutupōro',                 'rugby',                                    'FOO-too-POH-roh',
    { tags: ['culture'], note: 'New Zealand\'s national sport, deeply tied to Māori identity through the All Blacks and the haka.' }),
  V('mi-unit-24', 'poiwhana',                  'soccer / football',                        'POH-ee-FAH-nah' ),
  V('mi-unit-24', 'kirikiti',                  'cricket',                                  'KEE-ree-KEE-tee', { note: 'From English "cricket".' }),
  V('mi-unit-24', 'kapua-ā-rorohiko',          'cloud (computing)',                        'KAH-poo-ah-AH-ROH-roh-HEE-koh' ),

  // ═══════════════ Unit 25 — Advanced Concepts ═══════════════════════════════
  V('mi-unit-25', 'Te Tiriti o Waitangi',      'The Treaty of Waitangi',                   'teh TEE-ree-tee oh WHY-tah-ngee',
    { tags: ['culture'],
      note: 'Signed in 1840 between the Crown and over 500 Māori rangatira. The founding document of modern NZ — and the Māori text (Te Tiriti) and English text differ critically. The Māori text retains tino rangatiratanga.' }),
  V('mi-unit-25', 'tino rangatiratanga',       'absolute self-determination',              'TEE-noh RAH-ngah-TEE-rah-TAH-ngah',
    { tags: ['culture'],
      note: 'The chiefly authority Article 2 of Te Tiriti guarantees to Māori over their lands, villages, and treasures. The phrase at the centre of Māori political claims for 180 years.' }),
  V('mi-unit-25', 'kaupapa',                   'topic / project / cause',                  'KOH-pah-pah',
    { tags: ['culture'], note: 'The reason for gathering, the purpose at hand, the matter under discussion. "Kaupapa Māori" = a Māori-centred approach.' }),
  V('mi-unit-25', 'tikanga',                   'customary law / right way',                'TEE-kah-ngah', { tags: ['culture'] }),
  V('mi-unit-25', 'ōritetanga',                'equality',                                 'OH-ree-teh-TAH-ngah', { tags: ['culture'] }),
  V('mi-unit-25', 'tino aroha',                'deep love / compassion',                   'TEE-noh AH-roh-hah', { tags: ['culture'] }),
  V('mi-unit-25', 'pono',                      'truth / faithful',                         'POH-noh', { tags: ['culture'], note: 'A core value — being true, faithful, honest.' }),
  V('mi-unit-25', 'tika',                      'right / correct / just',                   'TEE-kah',
    { tags: ['culture'], note: 'Both "factually correct" and "morally right". The root of "tikanga".' }),
  V('mi-unit-25', 'kāwanatanga',               'government / governorship',                'KAH-wah-nah-TAH-ngah',
    { tags: ['culture'], note: 'From "kāwana" (governor, from English) + tanga. The Crown\'s right of governance under Te Tiriti Article 1 — contrasted with rangatiratanga.' }),
  V('mi-unit-25', 'pakanga',                   'war / battle',                             'PAH-kah-ngah', { tags: ['culture'] }),
  V('mi-unit-25', 'rangimārie',                'peace',                                    'RAH-ngee-MAH-ree-eh', { tags: ['culture'], note: 'Pō mārie = "peaceful night" — share the root.' }),
  V('mi-unit-25', 'mātauranga',                'knowledge / wisdom',                       'MAH-tow-RAH-ngah',
    { tags: ['culture'], note: 'Mātauranga Māori = Māori knowledge system. Recognised in law and increasingly in NZ research alongside Western science.' }),
];
